### ISSUE TITLE
Error with quote `

### ISSUE THREAD

**Issue by XadillaX** [commitizen/cz-cli#105]
```
? Write a short, imperative tense description of the change:
 \`myUp\` is still false after upping
```

or

```
? Write a short, imperative tense description of the change:
 `myUp` is still false after upping
```

They make no sense.

**Comment by jimthedev** [comment]
I don't understand. Is something breaking at that point? Afaik there's not a test case for this. Would you be able to put in a PR to cover this in a test case?

**Comment by Guria** [comment]
@jimthedev just try ``` `echo smth` ``` in commit message and it would be evaled in bash. `cz-customizable` has fix for it by escaping.
