### ISSUE TITLE
Error: ReferenceError: Map is not defined

### ISSUE THREAD

**Issue by zg9uagfv** [commitizen/cz-cli#125]
`
#:uname -ra
Linux 3.13.0-76-generic #120-Ubuntu SMP Mon Jan 18 15:58:41 UTC 2016 i686 i686 i686 GNU/Linux

＃:npm install -g commitizen

＃:~/Project/t$ sudo commitizen init cz-conventional-changelog --save --save-exact --force
Attempting to initialize using the npm package cz-conventional-changelog
Error: ReferenceError: Map is not defined
＃:~/Project/SyncClient$ 
`

**Comment by bkapicka** [comment]
I had the same error when using Node v0.10.36.  Updating to v4.2.6 resolved the issue in my case.

**Comment by jimthedev** [comment]
@bkapicka is correct. At this time only 0.12 and greater are tested. We will continue to deprecate node versions in the future as stable versions come out.

**Comment by zg9uagfv** [comment]
@bkapicka i got it!thanks.

**Comment by xetra11** [comment]
As I tried to init my repo with commitizen I got following message:

`Attempting to initialize using the npm package cz-conventional-changelog
Error: ReferenceError: Map is not defined
`
npm -v // 1.3.10

can anybody guide me to get this to work? really love it!

**Comment by jimthedev** [comment]
@xetra11 What version of Node are you using? You can find this by running `node -v`.
I do not know how version 1.3.10 of npm would work with commitizen. Please upgrade to at least the latest version of 2 or ideally version 3.

**Comment by xetra11** [comment]
@jimthedev sorry dude I've mistaken node with npm so I was updating npm all the time ;)
