### ISSUE TITLE
Fail a build if the commit is not in the standard format

### ISSUE THREAD

**Issue by tusharmath** [commitizen/cz-cli#129]
How can I ENFORCE using CZ? Can I check the commit messages on Travis?

**Comment by tusharmath** [comment]
ANY BODY THERE?

**Comment by Guria** [comment]
There is pre commit hooks for that, but I have tried it to use with travis npmjs.com/package/validate-commit-msg

**Comment by tusharmath** [comment]
Wow! Thanks @Guria
