### ISSUE TITLE
Ability to re-run a commit if it fails

### ISSUE THREAD

**Issue by lricoy** [commitizen/cz-cli#132]
Sometimes, when a pre_commit hook is configured, our commit will fail. It would be helpful to have a way to pass something like `--retry` so we won't need to enter the message again.

**Comment by jimthedev** [comment]
Good point. Since this is a cli, we don't really have any place to store this commit over time. Would it be just the last 1 commit that you'd want cached?

**Comment by lricoy** [comment]
Yeah, at first that would be the case. The use case would be to re-run it after fixing the tests or coverage.

**Comment by kentcdodds** [comment]
I'd love this feature. Having to fill out the prompts again because of a long error is super annoying. I'd want it to show me the message before it commits though.

**Comment by jimthedev** [comment]
Where can we store this info? A text file cache in the repo? We'd need to add it to .gitignore but at least then the cash would go with the repo if it gets moved.

**Comment by kentcdodds** [comment]
Yeah, put it in the repo and document the need to gitignore it

**Comment by jimthedev** [comment]
Gave it a bit more thought. We can do this simply by have a filesystem based cache in the user's home directory.

The cache keys will be a paths to repo roots, the value will be a serialized command that was going to be executed. I will work on this soon. I think we can offer it w/o a breaking change or .gitignore changes. Sure if you move a folder around you'll lose the ability to use the retry command between moves, but that probably an ok tradeoff.

**Comment by kentcdodds** [comment]
What if you used the temp directory instead? That way you don't put more stuff in the already-too-full user home...

**Comment by jimthedev** [comment]
I'm thinking of using home-or-tmp.

**Comment by jimthedev** [comment]
This will be released as an undocumented feature in 2.7.0. I will add tests and docs in 2.7.1 but wanted to see if you folks could test it. You can use it but running `git cz --retry`.

**Comment by lricoy** [comment]
I will take a look right away.

**Comment by jimthedev** [comment]
Looks like the node 0.12 build failed. @lricoy  I'll have to look at it before 2.7.0 releases

**Comment by jimthedev** [comment]
Ok, looks like it was me just being dumb and forgetting that Object.assign isn't available in node 0.12. Using lodash's alternative for now. This fix is released as [2.7.1](https://github.com/commitizen/cz-cli/releases/tag/v2.7.1). Would appreciate any feedback!

**Comment by jimthedev** [comment]
This is in the [docs](http://commitizen.github.io/cz-cli/) as of https://github.com/commitizen/cz-cli/commit/f1c719fd892cabbfc070b4275f3c33d7000b978a

**Comment by lricoy** [comment]
It worked fine for me @jimthedev

**Comment by jimthedev** [comment]
@lricoy Great. Thanks!

**Comment by lricoy** [comment]
One thing to note. If using from a npm script defined on package.json. The syntax required double `--`, as npm requires `--` for passing args to `npm run` and the `--retry` being the argument itself: 

`npm run commit -- --retry`

commit only being an alias to git-cz on node-modules/bin
```
  "scripts": {
      "commit": "git-cz",
  },
```

**Comment by kentcdodds** [comment]
See also: https://github.com/bahmutov/npm-quick-run :-)

**Comment by lricoy** [comment]
Cool @kentcdodds
