### ISSUE TITLE
Should nodemon be a dep instead of devdep?

### ISSUE THREAD

**Issue by remy** [commitizen/cz-cli#151]
I've not looked at this in detail yet, but when I installed a package that had `commitizen` as a `devDependencies` it also appeared to install `nodemon` - which is (I suspect) used for development in commitizen. 

So should nodemon be moved to `devDependencies` instead of `dependencies`?

**Comment by jimthedev** [comment]
Yes. You are correct. There is a pr for this and other node dev deps. I
will merge when I make it to a computer today.

**Comment by remy** [comment]
Darnit - I checked the issues for any mention it being handled, but totally missed the PRs! Sorry! (I'll close as it's in hand).

**Comment by jimthedev** [comment]
Don't worry. I'm way behind on updates. Not your fault :p

Thanks for the feedback.

**Comment by jimthedev** [comment]
@remy Finally fixed our CI issues. This is released in [v2.5.1](https://github.com/commitizen/cz-cli/releases/tag/v2.5.1).
