### ISSUE TITLE
`gulp` and `gulp-git` are required dependencies for at least v2.6.0

### ISSUE THREAD

**Issue by colinrymer** [commitizen/cz-cli#153]
Both `gulp` and `gulp-git` are required to run cz-cli, but are only listed as `devDependencies`, not normal `dependencies`.

**Comment by marionebl** [comment]
Sorry for introducing this with https://github.com/commitizen/cz-cli/commit/a8c40a9a6a1009dc80a5e0cb17591b8f1ac9aa05. I was a bit overzealous optimizing and getting rid of the `graceful-fs` deprecations there.

**Comment by colinrymer** [comment]
No worries. I was glad to see stuff get moved to devDeps, and the bug was easily resolved by just manually installing gulp and gulp-git for now. :+1:

**Comment by jimthedev** [comment]
I'll try to merge Marios PR tonight when at a computer again
