### ISSUE TITLE
NPM@3 support

### ISSUE THREAD

**Issue by jimthedev** [commitizen/cz-cli#16]
Npm's flat modules break existing commitizen functionality. In order to fix these issues there needs to be some major architectural changes in Commitizen 2 and in the adapters.

**Comment by baer** [comment]
21 hours before me! Looks like I'm running into the same problem - here is a little extra error info:

```
commitizen
Potentially unhandled rejection [3] Error: Error loading "node_modules/word-wrap/index" at file:/Users/ebaer/dev/personal/freelance/lnc/sales-backbone/node_modules/cz-conventional-changelog/node_modules/word-wrap/index.js
Error loading "node_modules/word-wrap/index" from "index" at file:/Users/ebaer/dev/personal/freelance/lnc/sales-backbone/node_modules/cz-conventional-changelog/index.js
ENOENT: no such file or directory, open '/Users/ebaer/dev/personal/freelance/lnc/sales-backbone/node_modules/cz-conventional-changelog/node_modules/word-wrap/index.js'
    at Error (native)
```

**Comment by olalonde** [comment]
Running in same problem.

**Comment by jimthedev** [comment]
@baer @olalonde Thanks for your patience. This is a known issue with npm3 and thankfully I am almost done with a test suite and npm3 fix. Should be out in the next few days I'd imagine.

**Comment by olalonde** [comment]
Thanks. I reverted to an older release for now.

**Comment by jimthedev** [comment]
Quick update. This is coming along nicely in 2.x. 
![screen shot 2015-10-15 at 11 33 21 am](https://cloud.githubusercontent.com/assets/108938/10520613/b1926526-7330-11e5-942d-6e336b8f3ce1.png)
