### ISSUE TITLE
Question - how `cz` is hooked/aliased to git

### ISSUE THREAD

**Issue by sarbbottam** [commitizen/cz-cli#166]
**No issue with `cz-cli`**. On `npm install -g commitizen` I am able to use `git cz`; as stated 
>>Now, simply use `git cz` instead of `git commit` when committing.

---

Please excuse my ignorance , I would like to know, how `cz` is `hooked/aliased` to git. 

I have following [`git alias`](https://github.com/sarbbottam/conf-files/blob/master/git-confs/gitconfig#L12-L21) set.

```
[alias]
  cl = clone
  br = branch

  co = checkout

  st = status
  df = diff
  all = add --all
  ci = commit
```

So, I could use `git ci` instead of `git commit`, but I could not figure out how `git cz` is working?

Is it because there is an executable `prefix`ed with `git` in the `PATH`?

Any pointer would be helpful. Thanks!!

**Comment by jimthedev** [comment]
Hi there! Good question and you are exactly right. 

Commitizen is what's called a custom git command. These work by, as you said, [a filename convention](https://github.com/git/git/blob/56331f8727b0c2e7dc713b728eaf1e5843422cb7/git.c#L553). In theory all you need to do is put an executable called git-mysweetcommand in your PATH. In practice, in Node, you need to do a bit more:

You need to create two files (git-mysweetcommand and git-mysweetcommand.cmd), I usually put them in ./bin in my project. The one without an extension is for *Nix and the one with .cmd is for Windows.

Next, run `chmod +x git-mysweetcommand` to allow it to be executed by git on *nix.

Now you also need to add a `bin` key to your package.json to tell Node to make the binaries available in the path. Note that Node's convention here is to add the .cmd extension on the end of the command in Windows:

```
 "bin": {
    "git-mysweetcommand": "./bin/git-mysweetcommand"
  },
```

Lastly, you need to actually add some content to ./bin/git-mysweetcommand and ./bin/git-mysweetcommand.cmd.

**./bin/git-mysweetcommand**
This just executes a javascript file in node. You'll have to create ./bin/git-mysweetcommand.js and can use it as the entry point for your application on both Windows and *Nix.

```
#!/usr/bin/env node

require('./git-mysweetcommand.js');
```

**./bin/git-mysweetcommand**
This is a trick to basically just execute the other file (the one without the .cmd) in node.

```
@node "%~dpn0" %*
```

That's pretty much it. Obviously once you're in git-mysweetcommand.js you'll need to do whatever it is that you want to do! I haven't dug much into how git aliases and custom commands work together but would be interested to hear what you come up with.

**Comment by sarbbottam** [comment]
Thanks @jimthedev, this could be the **best explanation**!! :100:

**Comment by jimthedev** [comment]
@sarbbottam :+1: Happy to help.

**Comment by LitileXueZha** [comment]
It seems that a "default known" usage of Git... Although I couldn't find some useful information `"git custom commands"` on offical [git-scm.com](https://git-scm.com/doc), but google it helps me out.

If you have a executable file named `git-hellocmd` in system envrionment `PATH`, then you can:
```shell
$ git hellocmd
```

Note this is absolutely not same with Git aliases.

**Comment by dc-orz** [comment]
> Hi there! Good question and you are exactly right.
> 
> Commitizen is what's called a custom git command. These work by, as you said, [a filename convention](https://github.com/git/git/blob/56331f8727b0c2e7dc713b728eaf1e5843422cb7/git.c#L553). In theory all you need to do is put an executable called git-mysweetcommand in your PATH. In practice, in Node, you need to do a bit more:
> 
> You need to create two files (git-mysweetcommand and git-mysweetcommand.cmd), I usually put them in ./bin in my project. The one without an extension is for *Nix and the one with .cmd is for Windows.
> 
> Next, run `chmod +x git-mysweetcommand` to allow it to be executed by git on *nix.
> 
> Now you also need to add a `bin` key to your package.json to tell Node to make the binaries available in the path. Note that Node's convention here is to add the .cmd extension on the end of the command in Windows:
> 
> ```
>  "bin": {
>     "git-mysweetcommand": "./bin/git-mysweetcommand"
>   },
> ```
> 
> Lastly, you need to actually add some content to ./bin/git-mysweetcommand and ./bin/git-mysweetcommand.cmd.
> 
> **./bin/git-mysweetcommand** This just executes a javascript file in node. You'll have to create ./bin/git-mysweetcommand.js and can use it as the entry point for your application on both Windows and *Nix.
> 
> ```
> #!/usr/bin/env node
> 
> require('./git-mysweetcommand.js');
> ```
> 
> **./bin/git-mysweetcommand** This is a trick to basically just execute the other file (the one without the .cmd) in node.
> 
> ```
> @node "%~dpn0" %*
> ```
> 
> That's pretty much it. Obviously once you're in git-mysweetcommand.js you'll need to do whatever it is that you want to do! I haven't dug much into how git aliases and custom commands work together but would be interested to hear what you come up with.

That make sense :-)
