### ISSUE TITLE
Better support for breaking changes

### ISSUE THREAD

**Issue by tusharmath** [commitizen/cz-cli#192]
I think we can automate the prefixing of `BREAKING CHANGE:`. Right now one needs to explicitly type it and because of some silly typo, the release ends up being a feature release instead of a breaking release.

**Comment by jimthedev** [comment]
Sure, I like the idea. I'm not sure what would be the best way to improve this. Do you have any ideas for how to do this? I know [cz-customizable](https://github.com/leonardoanalista/cz-customizable) has some functionality for this. Maybe we could ask @leonardoanalista to push it back up into the cli?

**Comment by tusharmath** [comment]
@jimthedev I guess the issue should have been created https://github.com/commitizen/cz-conventional-changelog.

**Comment by leonardoanalista** [comment]
Yes @jimthedev Cz-customizable plugin adds the "breaking chance" words in uppercase.

**Comment by leonardoanalista** [comment]
One more difference from original conventional change oh:  we split the footer question in 2: one for close issues and other for breaking changes. This way we can add the handy words

**Comment by leonardoanalista** [comment]
I thing the question asked belong to the plugins, not comittizen
