### ISSUE TITLE
Signing git commit?

### ISSUE THREAD

**Issue by kwonoj** [commitizen/cz-cli#207]
Hi, I'm curious if it's possible to sign git commit (https://git-scm.com/book/uz/v2/Git-Tools-Signing-Your-Work#Signing-Commits). Just did quick try by passing `-S` as argument, seems not working, maybe I'm missing something.

**Comment by dealloc** [comment]
What error are you getting? Because I'm using commitizen and signing and I have no problems

**Comment by dealloc** [comment]
For anyone who stumbled upon this, you can sign your commits using ``` git cz -S ```
You might want to configure your GPG keys in your global config using ``` git config --global user.signingkey ```

I first tried running git cz with the --gpg-sign parameter but that seemed to fail. Maybe I'll open an issue for this

**Comment by dealloc** [comment]
In case anyone else stumbles upon this issue, you can perfectly sign your commits using ``` git cz -S ```
You'll have configure your GPG key in the global git config using ``` git config --global user.signingkey <key> ``` (see [here](https://git-scm.com/book/tr/v2/Git-Tools-Signing-Your-Work#GPG-Introduction) for more info).

I usually signed my commits using the ``` --gpg-sign parameter="email" ``` but passing parameters with  ``` -- ``` prefixes doesn't seem to work properly. But when I run ``` git cz -S ``` it works as I expect it to.

**Comment by dealloc** [comment]
@LinusU should we close this issue? It's not actually an issue and the author doesn't seem to respond anymore

**Comment by LinusU** [comment]
It works for me as well :+1:

**Comment by javierguzman** [comment]
Does anyone know how to make this work with husky? I have this "test -t 1 && exec < /dev/tty && npx cz --signoff --hook || true" but commits are still not signed-off.

Thank you in advance
