### ISSUE TITLE
git cz fails in this repo

### ISSUE THREAD

**Issue by sarbbottam** [commitizen/cz-cli#210]
```js
...
   "commitizen": {
      "path": "./node_modules/cz-conventional-changelog"
    },
...
```
<img width="929" alt="screen shot 2016-04-25 at 2 54 44 pm" src="https://cloud.githubusercontent.com/assets/949380/14800331/d2ffdf56-0af5-11e6-8597-7ad8757a5b50.png">

However, if I update `path` to `cz-conventional-changelog` instead of `./node_modules/cz-conventional-changelog`, it works as desired.

```js
...
   "commitizen": {
      "path": "cz-conventional-changelog"
    },
...
```

**Comment by jimthedev** [comment]
Hi @sarbbottam. Sorry for causing this issue. I described it a bit more in detail here including how it came about and why these kinds of issues are unlikely to come up in the future: https://github.com/commitizen/cz-conventional-changelog/issues/20#issuecomment-214931097

Basically. You need to update to the latest version of the commitizen cli (2.8.1 or greater). I see from your screenshot you are on a slightly older cli.

Again, my apologies for the inconvenience.

**Comment by sarbbottam** [comment]
No worries. Closing the issue, as the latest version addresses the issue. Thanks!!
