### ISSUE TITLE
using node 0.10.36 commitizen is broken

### ISSUE THREAD

**Issue by jessekoconnor** [commitizen/cz-cli#226]
When im using node 0.10.36, I cant use commitizen. I get the following error:

`git-cz

/sw/git-repo/apps/haakon-env/repos/translations/node_modules/commitizen/dist/commitizen/adapter.js:173
  var parsed = _path2.default.parse(inboundAdapterPath);
                              ^
TypeError: Object #<Object> has no method 'parse'
    at resolveAdapterPath (/sw/git-repo/apps/haakon-env/repos/translations/node_modules/commitizen/dist/commitizen/adapter.js:173:31)
    at gitCz (/sw/git-repo/apps/haakon-env/repos/translations/node_modules/commitizen/dist/cli/strategies/git-cz.js:77:35)
    at Object.bootstrap (/sw/git-repo/apps/haakon-env/repos/translations/node_modules/commitizen/dist/cli/git-cz.js:31:27)
    at Object.<anonymous> (/sw/git-repo/apps/haakon-env/repos/translations/node_modules/commitizen/bin/git-cz.js:2:34)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)

npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/Users/jesseoconnor/.nvm/v0.10.36/bin/npm" "run" "commit"
npm ERR! node v0.10.36
npm ERR! npm  v2.14.18
npm ERR! code ELIFECYCLE
npm ERR! @meltwater/translations@0.0.0-semantically-released commit: `git-cz`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the @meltwater/translations@0.0.0-semantically-released commit script 'git-cz'.
npm ERR! This is most likely a problem with the @meltwater/translations package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     git-cz
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @meltwater/translations
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls @meltwater/translations
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /sw/git-repo/apps/haakon-env/repos/translations/npm-debug.log
Jesses-MacBook-Pro:translations jesseoconnor$ npm --version
2.14.18
Jesses-MacBook-Pro:translations jesseoconnor$ node --version
v0.10.36`

**Comment by jimthedev** [comment]
Hi @jessekoconnor Thanks for reporting this. Unfortunately we do not support Node 0.10.  We currently test for version 0.12.* to 5.*. Currently 0.10 and 6.0 are unsupported. I think we probably could be more specific about support either in our package.json or in the README.md.

**Comment by LinusU** [comment]
@jimthedev We should probably add the engines and enginesStrict fields to package.json so that it wont install on 0.10

**Comment by jimthedev** [comment]
@LinusU I agree. Want to PR?

**Comment by LinusU** [comment]
Will do 👍

**Comment by LinusU** [comment]
#229

**Comment by jimthedev** [comment]
@LinusU Awesome. Can you change your commit message to conform with conventional-changelog? Thanks. 👍

**Comment by LinusU** [comment]
@jimthedev I'll fix it right away, would have been great to have #182 now ;)

**Comment by jimthedev** [comment]
@LinusU, I know, I would like it as well. :)

Unfortunately in the last month my wife's father passed away, I have a new job, a one year old daughter and my cars transmission just died so am a bit preoccupied with other things. Would be happy to take PRs but to be honest I will need help w/merging and publishing even. I will try to get something out but this is very low on my list at the moment. Thanks for the patience and let me know if you'd like to take anything over.

Cheers.

**Comment by LinusU** [comment]
@jimthedev I'm very sorry to hear that, I would be very happy to help out! I use commitizen at work every day so I have a very high interest in keeping it working as smooth as possible. I'm `linusu` at npm and you can see my username here on github.

Hope that everything works out for the better for you, best of luck!

**Comment by jimthedev** [comment]
@LinusU Added you to the team + npm. I think if you sign into Appveyor with your github account then you should also have admin access there for windows tests.

**Comment by LinusU** [comment]
Thanks man

**Comment by jimthedev** [comment]
10 is no longer supported and @LinusU added the engines tag so I am closing this. Thanks!
