### ISSUE TITLE
update Inquirer.js from 0.12.0 to 1.0.2 is a breaking change

### ISSUE THREAD

**Issue by leonardoanalista** [commitizen/cz-cli#227]
Hi guys, 

Update Inquirer.js from 0.12.0 to 1.0.2 is a breaking change:
https://github.com/commitizen/cz-cli/commit/a538dced#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R76

Maybe let the plugin maintainers know next time so we can prepare the fix. I'll update cz-customizable tonight or as soon as I can. 

cheers
Leonardo

**Comment by leonardoanalista** [comment]
I have fixed cz-customizable: https://github.com/leonardoanalista/cz-customizable/releases/tag/v4.0.0

**Comment by jimthedev** [comment]
@leonardoanalista So sorry for this. Totally my fault for labelling a breaking change as a fix. In the future this will not happen. In the rare event that it does I will open PRs on your repo to let you know of the fix. 

Jim

**Comment by leonardoanalista** [comment]
I would recommend to write end-2-end tests. Eg.: `commitizen + one adapter` to ensure no updates break the functionality. 
Commitizen only works integrated with at least one adapter. It makes sense to test them from a user perspective.
I noticed that the standard changelog adapter doesn't have any uni tests.

**Comment by LinusU** [comment]
Totally agree, it would be nice to get some tests up and running with some of the most popular adapters!

@leonardoanalista what do you think of #249, having the dependency in the adapter would mean that everyone could update at their own pace
