### ISSUE TITLE
2.8.1 does not commit

### ISSUE THREAD

**Issue by pmcelhaney** [commitizen/cz-cli#234]
OSX 10.11.3
Node 5.9.0

After upgrading from 2.7.6 to 2.8.1, `git cz` works normally but does not actually commit changes. The issue was introduced with 2.8.0.

**Comment by LinusU** [comment]
Which adapter are you using? See #249

**Comment by pmcelhaney** [comment]
It's a custom adapter. Looks like we need to update it.

**Comment by LinusU** [comment]
Yes, sorry about that, unfortunately a breaking change slipped through...

I would advise you to depend on `inquirier` in your adapter and not use the provided instance. That way your adapter can work wit both pre-2.8 and post-2.8 at the same time :+1:

**Comment by pmcelhaney** [comment]
Thanks, I was able to resolve the issue by depending on Inquirer directly and changing to the promise API. Also discovered this is a duplicate of #205.
