### ISSUE TITLE
Configure cache

### ISSUE THREAD

**Issue by dealloc** [commitizen/cz-cli#240]
Currently when using commitizen it dumps the commitizen.json file in the home directory (as described [here](https://github.com/commitizen/cz-cli#retrying-failed-commits)).
In Windows this doesn't exactly form a problem (you rarely see your homefolder), but when using Linux you're dropped right into the home folder when opening a file manager.
I'm no real fan of cluttering my home directory with config files and end up deleting the .json file every time, but this is rather cumbersome to do every time I open a file manager.

My suggestion is to allow configuring the path where the commitizen.json is stored or rename it to .comittizen.json or something so that it's hidden.

as you can see below, it really sticks out like a sore thumb
![1464038105](https://cloud.githubusercontent.com/assets/2164354/15484874/8085da8e-213c-11e6-9d11-41d09a6725c7.png)

**Comment by LinusU** [comment]
Totally agree, maybe we could use: https://github.com/LinusU/node-application-config-path

**Comment by dealloc** [comment]
I've taken a quick look at the source code of your package.
For Linux hosts you're using the ``` XDG_CONFIG_HOME ```, for example on my system (Arch linux) that variable isn't defined. I think it would be safed to use something like ``` HOME ``` (which the current implementation of commitizen uses) and put the cache in a subdir like .commitizen (which would be hidden due the "**.**" prefix

**Comment by LinusU** [comment]
If `XDG_CONFIG_HOME` isn't present it will use `$HOME/.config`, thus the final path will be `$HOME/.config/commitizen`

**Comment by dealloc** [comment]
Ah, seems I read a little too fast over the source, my apologies.
That seems like an ideal case! If I got the time I'll see about making a PR for this (but with my finals coming up I'm not certain I can)

**Comment by jimthedev** [comment]
What if we just make our config a dot file like proposed in: https://github.com/commitizen/cz-cli/pull/183?

At least then it would be hidden. I want to make sure whatever solution we come up with, it works on windows.
