### ISSUE TITLE
Messages with newlines are broken on Windows

### ISSUE THREAD

**Issue by rtomchinsky** [commitizen/cz-cli#286]
When commiting, when messages are split into lines, `git` will consider each line a new paragraph, meaning that paragraphs that are broken into many lines, such as [cz-conventional-changelog](https://github.com/commitizen/cz-conventional-changelog) emits, will result in an unexpected formatting of the final message.

I opened stevelacy/gulp-git#122 which allows gulp-git to pass multiline messages as expected, but to prevent breaking changes, it requires the message as either an array of paragraphs and the `multiline` option set to `true` or a string with `\n`s. It seems that simply changing [this line](https://github.com/commitizen/cz-cli/blob/master/src/git/commit.js#L21):
```javascript
operatingSystemNormalizedMessage = escapedMessage.split(/\r?\n/);
```
with this:
```javascript
operatingSystemNormalizedMessage = escapedMessage.replace('\r', '');
```
would solve the issue, unless I'm missing something.

I'll try to open a PR later when I have a chance, unless someone else wants to do it.

Thanks.

**Comment by marionebl** [comment]
Should be addressed with https://github.com/commitizen/cz-cli/commit/0d4e0d591cba474ae451ea53c9db9768257e202b as `gulp-git` no longer is a dependency

**Comment by LinusU** [comment]
Please reopen if problem persists
