### ISSUE TITLE
git: 'cz' is not a git command. See 'git --help'.

### ISSUE THREAD

**Issue by martinhbramwell** [commitizen/cz-cli#289]
I don't know how to deal with this.

I assumed it was simply a Path or symlink issue but got no where at all trying to understand how they work between `bash`, `npm`, `git` and `commitizen`.

**install**

     you@trykik:~/projects/tryCommitizen$  sudo npm install commitizen -g
     npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
     npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
     npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
     npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
     npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
     /home/you/.npm/bin/git-cz -> /home/you/.npm/lib/node_modules/commitizen/bin/git-cz
     /home/you/.npm/bin/commitizen -> /home/you/.npm/lib/node_modules/commitizen/bin/commitizen
     /home/you/.npm/lib
     └─┬ commitizen@2.8.2 
       ├─┬ chalk@1.1.3 
       │ ├── ansi-styles@2.2.1 
       │ ├── escape-string-regexp@1.0.5 
       │ ├─┬ has-ansi@2.0.0 

           :
           
       ├── lodash@4.11.1 
       ├── minimist@1.2.0 
       ├── shelljs@0.5.3 
       └── strip-json-comments@2.0.1 

**run**

     you@trykik:~/projects/tryCommitizen$ git cz
     git: 'cz' is not a git command. See 'git --help'.

     Did you mean one of these?
          am
          fsck
          gc
          mv
          rm

**.profile**

     you@trykik:~/projects/tryCommitizen$ cat ~/.profile

           :

     # set PATH so it includes user's private bin if it exists
     if [ -d "$HOME/bin" ] ; then
         PATH="$HOME/bin:$PATH"
     fi

     export PATH=~/npm/bin:$PATH

**.npmrc**

     you@trykik:~/projects/tryCommitizen$ cat ~/.npmrc 
     ; cli configs
     prefix = "~/.npm"

**system**

     you@trykik:~/projects/tryCommitizen$ lsb_release -a
     No LSB modules are available.
     Distributor ID:	Ubuntu
     Description:	Ubuntu 16.04.1 LTS
     Release:	16.04
     Codename:	xenial

     you@trykik:~/projects/tryCommitizen$ node --version
     v4.4.7

     you@trykik:~/projects/tryCommitizen$ npm --version
     3.10.3

     you@trykik:~/projects/tryCommitizen$ 

Please let me know if you need more information.

**Comment by pmcelhaney** [comment]
I'm not an expert on where npm puts things, but something I noticed is you have `export PATH=~/npm/bin:$PATH` but the symlink was created at `/home/you/.npm/bin/git-cz`. There's a "." before npm. Try changing that in your .profile file. 

If that doesn't work, you might have more luck on superuser.com.

**Comment by martinhbramwell** [comment]
That's very astute.  Thank you.

I have since killed the VM I was using to try that.  I believe ´NodeJS´ and ´npm´ were installed on it using ´apt´.

I am now on a different VM, where I know I installed ´NodeJS´ and ´npm´ with ´nvm´.

Now I have no problem at all.

**Comment by LinusU** [comment]
I believe that @pmcelhaney's solution is probably the correct one, please feel free to reopen if you have problems with it...

**Comment by elpddev** [comment]
I had to install `commitizen` ass global npm package fot `git cz` to work.

**Comment by stavalfi** [comment]
this should be documented somewhere.

**Comment by ghacosta** [comment]
If you don't want to install `commitizen` globally you can write the write the hooks as follows:
```
exec < /dev/tty && node_modules/.bin/cz --hook || true
```

**Comment by jacksparrow1111** [comment]
> If you don't want to install `commitizen` globally you can write the write the hooks as follows:
> 
> ```
> exec < /dev/tty && node_modules/.bin/cz --hook || true
> ```

Can you explain what `--hook || true` is doing

**Comment by Parth909** [comment]
First of all install commitizen using the package manager you prefer.
Along with it cz-conventional-changelog will also be added.

Then run the file binary directly using `npx cz`

![image](https://user-images.githubusercontent.com/59220026/146676972-9741d75f-5e43-46d2-8d19-4a027cff773f.png)

**Comment by jacksparrow1111** [comment]
> First of all install commitizen using the package manager you prefer. Along with it cz-conventional-changelog will also be added.
> 
> Then run the binary directly using `npx cz`
> 
> ![image](https://user-images.githubusercontent.com/59220026/146676972-9741d75f-5e43-46d2-8d19-4a027cff773f.png)

Thanks ! It works

**Comment by jacksparrow1111** [comment]
> First of all install commitizen using the package manager you prefer. Along with it cz-conventional-changelog will also be added.
> 
> Then run the binary directly using `npx cz`
> 
> ![image](https://user-images.githubusercontent.com/59220026/146676972-9741d75f-5e43-46d2-8d19-4a027cff773f.png)

Thanks @Parth909 ! It works now

**Comment by jacksparrow1111** [comment]
> If you don't want to install `commitizen` globally you can write the write the hooks as follows:
> 
> ```
> exec < /dev/tty && node_modules/.bin/cz --hook || true
> ```

@ghacosta This doesn't work

**Comment by anied** [comment]
> > If you don't want to install `commitizen` globally you can write the write the hooks as follows:
> > ```
> > exec < /dev/tty && node_modules/.bin/cz --hook || true
> > ```
> 
> @ghacosta This doesn't work

It worked for me-- OSX, using it for a Husky v8 setup.

**Comment by shady-abdelhamid** [comment]
> && node_modules/.bin/cz

you have to make the file executable
`chmod +x .husky/prepare-commit-msg`
