### ISSUE TITLE
Use npm's config object, deprecate czConfig

### ISSUE THREAD

**Issue by jimthedev** [commitizen/cz-cli#30]
Per @killswitch and @kentcdodds in [this original issue](https://github.com/commitizen/cz-cli/issues/9). We should be using npm's config object and not our own key. We want to be good package.json citizens after all. :+1: 

The main reason that this bad practice exists is that config loader originally came from jscs and thus followed their perhaps naive convention. The good news is we can easily add it and migrate to it being the default because their loader is pretty robust.

Things needed for this to happen:

- [x] Need to add some more robust tests to areas of the codebase that would be impacted by this change.
- [x] Add config.cz as the highest level priority option in the configLoader (note, we still need to support czConfig for now, but can add a deprecation warning in the cli to get people to switch)
- [x] Change `commitizen init` to use the config.cz location by default to encourage new adoption.
- [x] Change the docs to reflect this change
- [x] Add deprecation warning to cli, potentially even put in PRs on gh.
- [ ] Eventually remove support for czConfig in 3.0.0 per @kentcdodds 

Hooray!

**Comment by kentcdodds** [comment]
:+1:

**Comment by killswitch** [comment]
:+1:

**Comment by jimthedev** [comment]
This is included in [2.3.0](https://github.com/commitizen/cz-cli/releases/tag/v2.3.0). Also created a #38 as a reminder to remove czConfig as a breaking change in 3.0.0.

**Comment by kentcdodds** [comment]
Cheers! Well done @jimthedev!

**Comment by killswitch** [comment]
Awesome work @jimthedev!
