### ISSUE TITLE
Document release process

### ISSUE THREAD

**Issue by LinusU** [commitizen/cz-cli#303]
@jimthedev I might be missing something obvious, but how do I cut a new release of this package?

The package.json seems to indicate that this is done with some sort of automation, but I don't know how to trigger it...

**Comment by marionebl** [comment]
@LinusU This appears to be automated via [semantic-release](https://github.com/semantic-release/semantic-release), see [travis](https://travis-ci.org/commitizen/cz-cli/jobs/149094918#L510). As the linked build line indicates, semantic-release expects a commit of type `fix` or `feat` or with a body/footer containing `BREAKING CHANGE: lorem ipsum` before creating a new release automatically.
