### ISSUE TITLE
catch some error when i upgrade the version to 2.8.5 

### ISSUE THREAD

**Issue by tomasky** [commitizen/cz-cli#324]
Just a non node project:

Error: Could not locate node_modules in your project's root directory. Did you forget to npm init or npm install?
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined

**Comment by tomasky** [comment]
I have configed  the `~/.czrc`  and it is ok before upgrading.

**Comment by LinusU** [comment]
Oh, this is probably because of #292, sorry about that.

@pmcelhaney how do you think that we should solve this?

**Comment by pmcelhaney** [comment]
We should consider the git root as the project's root directory. 

```sh
git rev-parse --show-toplevel
```

**Comment by LinusU** [comment]
Sounds perfect 👍 would you like to submit a pull request?

**Comment by pmcelhaney** [comment]
Sure, I'll do it tomorrow when I'm back in front of my computer.

**Comment by LinusU** [comment]
Fixed in 2.8.6, @tomasky can you confirm that it works?
