### ISSUE TITLE
Integrate adapter types with validate-commit-msg

### ISSUE THREAD

**Issue by adjohnson916** [commitizen/cz-cli#326]
It'd be nice if we integrate with [validate-commit-msg](https://github.com/kentcdodds/validate-commit-msg) so that it could use the same types as our chosen adapter.

Recently when working on separating the engine from the types in commitizen/cz-conventional-changelog#30 for commitizen/cz-conventional-changelog#29, I'd also proposed a new config for just types module (not just adapter module) in https://github.com/commitizen/cz-conventional-changelog/issues/29#issuecomment-238093618 - the point there was that the config would be consumable by other tools including `validate-commit-msg`, so they could know what types we're using.

Alternatively, we could encourage adapter modules to export their types, so that the adapter config could be detected by modules such as `validate-commit-msg` which could then require them and extract the types for their use.

FYI @LinusU @jimthedev @kentcdodds

**Comment by kentcdodds** [comment]
seems like a good idea, but honestly, I'm not really interested in making first-class integration between these two modules. I think that another module could wire these things together and I'd be happy to expose the right hooks to make that happen.

**Comment by adjohnson916** [comment]
@kentcdodds What type of hooks are you thinking? Could validate-commit-msg read from a config in package.json that could be shared by multiple modules?

**Comment by kentcdodds** [comment]
Honestly, I'm not really interested in maintaining `validate-commit-msg` to do too much more than it's doing now. If you want to make a PR and it looks good, I'll give you commit/publish access and you can own it to do whatever you want. :)
