### ISSUE TITLE
Configure commitizen.json location - MacOS

### ISSUE THREAD

**Issue by racer1988** [commitizen/cz-cli#339]
As https://github.com/commitizen/cz-cli/issues/240 states, the commitizen.json is saved in the home folder, which is quite annoying.

I have not found any way to change that. 

If there is just a configuration to set, it would be interesting to write a README section about it.

**Comment by jimthedev** [comment]
@racer1988 Can you expand on what is annoying about the file being in the home directory? The current leaning is to move commitizen.json into .commitizen.json so that it is hidden. Is there some other use case where it should be in the node_modules folder instead?

**Comment by racer1988** [comment]
It is fine also to add the dot in front so it will be hidden.

**However** to avoid future changes again, I would tend to think we align to many other command line tools by creating a **folder called .commitizen** and add the cache file inside.

This way we can use the folder for many more configuration if needed.

(examples of config/cache folders are .subversion, .config for git, .iterm2, .vim, .gem, .dropbox., .cocoapods, .npm, .m2, android, .wireshark, .gnupg, .cordova etc etc etc..)

**Comment by jimthedev** [comment]
Closed by #400. You can now delete the commitizen.json. We might need to add a command line alert if this file is found that it is now safe to delete that file.
