### ISSUE TITLE
Empty lines in commit message

### ISSUE THREAD

**Issue by brokenmass** [commitizen/cz-cli#373]
If a commit message generated by a prompter contains new lines (`\n`) , commitizen split those across multiple `-m` commands generating erroneous empty lines in the comment
https://github.com/commitizen/cz-cli/blob/master/src/git/commit.js#L17

original message (and expected result)

```
perf: remove graphiteWidth option

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas id pulvinar mi, 
at porttitor dolor. Vivamus id ultricies tellus. Sed fringilla massa a urna venenatis 
sodales. Morbi mattis aliquam dui tempor efficitur. Maecenas ut velit at enim 
imperdiet convallis.

BREAKING CHANGE: The graphiteWidth option has been removed. 
The default graphite width of 10mm is always used for performance reason.

Issues: #1234
```

gets committed as : 

```
perf: remove graphiteWidth option

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas id pulvinar mi, 

at porttitor dolor. Vivamus id ultricies tellus. Sed fringilla massa a urna venenatis 

sodales. Morbi mattis aliquam dui tempor efficitur. Maecenas ut velit at enim 

imperdiet convallis.

BREAKING CHANGE: The graphiteWidth option has been removed. 

The default graphite width of 10mm is always used for performance reason.

Issues: #1234
```

this issue occurred from version 2.8.3 where gulp-git was removed.
on version 2.8.2 the output is correct

I strongly suggest to don't split the commit in multiple `-m` instructions as that would the formatting imposed by the prompter and eventually lead to a wrongly parsed (by conventional changelog) commit message, but instead just rely on parser correctness

**Comment by brokenmass** [comment]
any updates on this issue ?

**Comment by jimthedev** [comment]
Thanks I'll look into this.

**Comment by jimthedev** [comment]
Ok I think this takes care of it. We need to wait until the CI tests run, but I'll ask you to check on it once the next version is out.
