### ISSUE TITLE
Change request: README "(add sudo if on OSX/Linux)" part

### ISSUE THREAD

**Issue by vass-david** [commitizen/cz-cli#391]
It's not OK to encourage somebody to use sudo for installing global packages.
Installing anything with `sudo` is generally not recommended even by npm itself. User should set `prefix` parameter in local `.npmrc` to some local path (e.g. `/Users/yourusername/.npm`). Then you don't have to use sudo, since all global packages will be installed in your local folder.

I know it's not anything `cz-cli` development related but it caught my eye instantly when I saw that.

**Comment by LinusU** [comment]
Agreed, PR welcome 👍

**Comment by vass-david** [comment]
https://github.com/commitizen/cz-cli/pull/396
