### ISSUE TITLE
Support for scoped adapters?

### ISSUE THREAD

**Issue by ryanvanoss** [commitizen/cz-cli#403]
Currently the [`resolveAdapterPath`](https://github.com/commitizen/cz-cli/blob/master/src/commitizen/adapter.js#L128) uses Node's `path.parse` method, and examines the `dir` property to determine if the adapter path is an npm module name, or a path.

[adapter.js:129-131](https://github.com/commitizen/cz-cli/blob/master/src/commitizen/adapter.js#L129-L131)
```javascript
// Check if inboundAdapterPath is a path or node module name
let parsed = path.parse(inboundAdapterPath);
let isPath = parsed.dir.length > 0;
```

However, this will incorrectly assign [scoped packages](https://docs.npmjs.com/misc/scope) as paths (e.g. `inboundAdapterPath === '@foo/bar'`).

Is there a plan to support scoped packages?

**Comment by jimthedev** [comment]
It hasn't be brought up yet but yes we will need a fix for this.

**Comment by jimthedev** [comment]
Patch for this is coming.

**Comment by jimthedev** [comment]
Release will happen as soon as I can get CI to work.

**Comment by ryanvanoss** [comment]
Good stuff, thanks!

**Comment by jimthedev** [comment]
Released in https://github.com/commitizen/cz-cli/releases/tag/v2.9.1
