### ISSUE TITLE
Typeahead for the radio selections

### ISSUE THREAD

**Issue by jpnelson** [commitizen/cz-cli#423]
This would speed up committing time heaps for me, due to the way our adapters work.

Happy to make a PR for this if it would be accepted.

**Comment by jpnelson** [comment]
https://github.com/SBoudrias/Inquirer.js/issues/505

**Comment by LinusU** [comment]
This would be awesome, let's follow the development of the issue at Inquirer.js

**Comment by jpnelson** [comment]
Looks like it's a no-go for addition to inquirer, but https://github.com/mokkabonna/inquirer-autocomplete-prompt could be added to cz-cli.

What do you think about that?

**Comment by jimthedev** [comment]
Each adapter requires their own prompter so it would be a PR to
cz-conventional-changelog but I'd imagine that we'd consider it.

-- 
Jim ForCy

**Comment by jimthedev** [comment]
Looks like inquirer is going to let plugins handle this. I prefer to do the same for now. Again, if you can get it working I'd certainly accept a PR in cz-conventional-changelog or any of the other adapters.

**Comment by achillesrasquinha** [comment]
@jimthedev Interested in considering this!
