### ISSUE TITLE
Why is feat abbreviated, when refactor is not?

### ISSUE THREAD

**Issue by axefrog** [commitizen/cz-cli#425]
You're not abbreviating "refactor", and "feature" is shorter anyway. Why abbreviate only the latter?

**Comment by jimthedev** [comment]
Good question :) you'll have to ask Google, they wrote the original set.
Now a bunch of the ecosystem is built on it.

-- 
Jim ForCy

**Comment by axefrog** [comment]
Dang. Well I'm out. I'll build my own :D

**Comment by jimthedev** [comment]
Good luck! You can make an adapter but you may need to check to see how
semantic release and other tool chains respond.

-- 
Jim ForCy

**Comment by axefrog** [comment]
Ah, this is just for my own projects. I don't expect others to necessarily follow suit.
