### ISSUE TITLE
How to add custom commit types?

### ISSUE THREAD

**Issue by emcniece** [commitizen/cz-cli#43]
Is it possible to create new `type(scope): title...` commit types? We're using this in tandem with clog and we have some custom commit types defined for the changelog.

**Comment by jimthedev** [comment]
The easiest way to do this is to create an adapter.

To do this:
1. Fork the [commitizen/cz-conventional-changelog](https://github.com/commitizen/cz-conventional-changelog) repo.
2. Change the package.json's name field to your new adapter name (ie. cz-emcniece-changelog) and set the version field to 1.0.0.
3. Edit index.js to have your custom types.
4. `npm publish` when you're ready to publish your adapter to npm.
5. In any repo you want to use your new adapter you can just run `commitizen init cz-emcniece-changelog --save-dev --save-exact`. If the repo already has an adapter installed then you a can add the `--force` flag to that last command and it will overwrite your old config.

**Comment by emcniece** [comment]
Awesome - thanks so much for the guide!

**Comment by talohana** [comment]
Almost 5 years later, but is there any "easier" solution to this rather than forking and publishing an adapter?

(Reviving this issue only since it's the first that comes up when searching for this)

**Comment by pminf** [comment]
@talohana You can override all types by specfiing your own inside your projects package.json:
```
"config": {
    "commitizen": {
      "path": "./node_modules/cz-conventional-changelog",
      "types": {
        "foo": {
          "title": "foo",
          "description": "This is a foo change."
        },
        "bar": {
          "title": "bar",
          "description": "This is a bar change."
        }
      }
    }
  }
```
This will replace the already defined types from the adapter. I don't know if there is a way to only add custom types.

See also https://github.com/commitizen/cz-conventional-changelog#configuration

**Comment by stdedos** [comment]
What about _just adding_ types, **instead of** `types` blinding overriding base spec?
