### ISSUE TITLE
Possible to use multiple adapters?

### ISSUE THREAD

**Issue by brandondurham** [commitizen/cz-cli#434]
I’m using `cz-conventional-changelog` but would also love to use `cz-customizable` to allow for creating custom types. Is it possible to use both alongside each other?

This is my `package.json` config currently:
```
"config": {
  "commitizen": {
    "path": "cz-conventional-changelog"
  },
  "cz-customizable": {
    "config": "internals/scripts/commitizen/commitizen-customizable.js"
  }
},
```

**Comment by brandondurham** [comment]
I now realize `cz-customizable` consumes the functionality of `cz-conventional-changelog`, but I suppose the question still stands.

**Comment by jimthedev** [comment]
It is currently not possible to consume multiple adapters. In a future architecture it would be neat to be able to have composable adapters.

**Comment by brandondurham** [comment]
Thanks, Jim. I lucked out on this one since one was seemingly a fork of another. 💯

**Comment by jimthedev** [comment]
You sure did!

**Comment by wizardnet972** [comment]
any news? is it possible now?

**Comment by MrLeihe** [comment]
is great to use multiple adapter

**Comment by crs1138** [comment]
So it seems one can't use `cz-emoji` and `cz-conventional-changelog` at the same time. I wish I found this thread earlier.

**Comment by mehmetnyarar** [comment]
any update on this? I'd like to use `cz-conventional-changelog` and `cz-emoji` together if possible.

**Comment by xAirx** [comment]
No update?
