### ISSUE TITLE
Don't throw the error when git-cz fails

### ISSUE THREAD

**Issue by lukaszmoroz** [commitizen/cz-cli#436]
Right now when the command fails, it prints the whole stack trace. Is it really necessary?

**Comment by jimthedev** [comment]
I'm open to hearing arguments or PRs to improve this functionality. Currently we give you everything because a git hook including test output may have failed and we want you to see which tests failed.

**Comment by lukaszmoroz** [comment]
It adds a lot of noise and is not very informative. See:

Trying to `git cz` with empty index:
```
.../node_modules/commitizen/dist/cli/strategies/git-cz.js:87
      throw new Error('No files added to staging! Did you forget to run git add?');
      ^

Error: No files added to staging! Did you forget to run git add?
    at .../node_modules/commitizen/dist/cli/strategies/git-cz.js:87:13
    at .../node_modules/commitizen/dist/commitizen/staging.js:25:5
    at ChildProcess.exithandler (child_process.js:197:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:511:12)
```

Combined with a `commit-msg` hook:
```
nps executing: conventional-changelog-lint -e
⧗   input: feat: foo.
✖   message may not end with full stop [subject-full-stop]
✖   found 1 problems, 0 warnings
The script called "lint.commit" which runs "conventional-changelog-lint -e" failed with exit code 1 https://github.com/kentcdodds/nps/blob/v5.1.0/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code

> husky - commit-msg hook failed (add --no-verify to bypass)
> husky - to debug, use 'npm run commitmsg'
.../node_modules/commitizen/dist/cli/strategies/git-cz.js:102
        throw error;
        ^

Error: git exited with error code 1
    at ChildProcess.<anonymous> (.../node_modules/commitizen/dist/git/commit.js:50:26)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

All these errors should be handled IMO and turned into non-zero exit with just the error message printed.

**Comment by jimthedev** [comment]
Fair enough. Would you be interested in putting in a PR?

-- 
Jim ForCy

**Comment by lukaszmoroz** [comment]
Sure

**Comment by bm-stschneider** [comment]
commitizen@2.9.6 this is still in right?

**Comment by raisedadead** [comment]
@bm-stschneider don.t think so. This was merged by never published? /cc @jimthedev

**Comment by vinyfc93** [comment]
## commitizen@2.9.6

```bash
/usr/local/lib/node_modules/commitizen/dist/cli/strategies/git-cz.js:87
      throw new Error('No files added to staging! Did you forget to run git add?');
      ^

Error: No files added to staging! Did you forget to run git add?
    at /usr/local/lib/node_modules/commitizen/dist/cli/strategies/git-cz.js:87:13
    at /usr/local/lib/node_modules/commitizen/dist/commitizen/staging.js:25:5
    at ChildProcess.exithandler (child_process.js:264:7)
    at ChildProcess.emit (events.js:160:13)
    at maybeClose (internal/child_process.js:943:16)
    at Socket.stream.socket.on (internal/child_process.js:363:11)
    at Socket.emit (events.js:160:13)
    at Pipe._handle.close [as _onclose] (net.js:562:12)
```

@bm-stschneider, @raisedadead and @jimthedev.

Is this right?

**Comment by jimthedev** [comment]
Did you run got add myfile.md first?

**Comment by vinyfc93** [comment]
Sorry but I do not know this file, where could I find it?

**Comment by jimthedev** [comment]
No, you would replace that with your file that you want to commit. Or you
could use git add . for all changed files.

-- 
Jim ForCy

**Comment by vinyfc93** [comment]
Sorry but I do not know this file, where could I find it?
If you're talking about adding the file in the git stage, myfile.md being a file from my project, that's not what I'm talking about.
My question has to do with why the exit is not treated to show a more friendly and easy-to-understand message

**Comment by jimthedev** [comment]
Please see https://github.com/commitizen/cz-cli/issues/436#issuecomment-301452208 which explains that we are open to a PR for better functionality but at the moment we give everything since it is helpful when running in a git hook scenario. I will point out that `Error: No files added to staging! Did you forget to run git add?` is right there. How would you prefer the message to be written? Please offer suggestions.

**Comment by vinyfc93** [comment]
@jimthedev,

Thanks for explanation and calm, had not seen the explanation above, sorry for this. I will consider creating PR soon enough.

keep up the good work! =]
