### ISSUE TITLE
Not showing commit prompt

### ISSUE THREAD

**Issue by colebemis** [commitizen/cz-cli#441]
I ran `npm install --save-dev commitizen` then added `"cm": "git-cz"` to my npm scripts. When I run `npm run cm` I don't get a the nice prompt guiding me through a commit message. This is what I get instead: 
![image](https://cloud.githubusercontent.com/assets/4608155/26773342/c70f53ce-497f-11e7-834e-b115678b90c6.png)

How can I get commitizen to show the prompt?

**Comment by colebemis** [comment]
Hmm, I'm only having this problem when using the integrated terminal in VSCode.

**Comment by jimthedev** [comment]
Did you install an adapter?

**Comment by colebemis** [comment]
It started working. I'm not sure why though 🤔 I didn't change anything.

**Comment by jorge-sanz** [comment]
I have this problem normally every time I install commitizen the first time in a new computer.

**Comment by adriankremer** [comment]
could it be because you're firing git-cz in another subfolder containing a package.json? try to go up to the root pkg.

**Comment by jorge-sanz** [comment]
> could it be because you're firing git-cz in another subfolder containing a package.json? try to go up to the root pkg.

In my case I didn't follow the fully the instructions 😬 https://github.com/commitizen/cz-cli#conventional-commit-messages-as-a-global-utility

Sorry for disturbing 🙏

**Comment by viniciusteixeiradias** [comment]
Hey, I know this issue has already been closed, but I would like to know what the solution was? I am having exactly the problem mentioned. I've already tested with local and global commitizen, every time I'm redirected to this "strange prompt".
