### ISSUE TITLE
Finding a way to use `git commit`

### ISSUE THREAD

**Issue by micky2be** [commitizen/cz-cli#448]
I think it would be nice to setup a pre-commit hook to run commitizen when running the command `git commit`.

I would personally rather my team use a command they already know than learning a new one.
Make it easier when switching projects.

**Comment by jimthedev** [comment]
I would consider a PR with this functionality if it included some tests to show that it doesn't break existing tooling. People using commitizen bring a bunch of existing git commit hooks to the table and we'd need some way to still run those hooks and in the correct order with regards to commitizen.

**Comment by micky2be** [comment]
Alright, I'll take a look.

**Comment by thedaviddias** [comment]
@micky2be Any news on creating a PR for that?

**Comment by olgn** [comment]
@thedaviddias I've got one open at #615

**Comment by thedaviddias** [comment]
That's awesome @olgn, thanks!

**Comment by olgn** [comment]
@thedaviddias any feedback is appreciated!
