### ISSUE TITLE
disable "git commit"

### ISSUE THREAD

**Issue by dnepro** [commitizen/cz-cli#450]
Is there a way to disable the usage of "git commit" in a commitizen project?

**Comment by jimthedev** [comment]
Hi there. There's not a way to disable it `git commit`. You can use an alias or you can reject commits that don't match your schema though. See something like https://github.com/marionebl/commitlint

**Comment by dnepro** [comment]
Ok, that sounds also legitimate and i will definitly give it a try :) Thank you for the fast response!
