### ISSUE TITLE
support config file

### ISSUE THREAD

**Issue by zyy7259** [commitizen/cz-cli#460]
support `.czrc` or `cz.config.js` config file through https://github.com/davidtheclark/cosmiconfig

**Comment by prometheas** [comment]
I must first say that it's very courteous indeed that commitizen at least looks for its configs under a top-level `config` key in `package.json`, rather than forcing us to jam another bespoke key name in that file like so many other packages do, but… definitely this, please!

**Comment by Nargonath** [comment]
Another use case for this is when you want to gather all your configuration into one package ala `react-scripts`.

**Comment by fsmaia** [comment]
:+1: 
Any help wanted?

**Comment by travi** [comment]
is there something special desired about cosmiconfig that isn't handled currently? i've been using [`.czrc` files](https://github.com/travi/.github/blob/master/.czrc) in my projects for quite a while. here are the currently supported sources: https://github.com/commitizen/cz-cli/blob/a6adb3b1f7cc19c5a8f011d2c189de0dc03bfceb/src/commitizen/configLoader.js#L6

**Comment by Nargonath** [comment]
From what I remembered since my last post, what I wanted to do is "import" my configuration from a package instead of having it in the root folder i.e for `prettier` I can do that:
```js
// .prettierrc.js
const config = require('my-prettier-config');

module.exports = config;

```

From what I understand such behavior was not possible at least in 2019 when I commented.

**Comment by fsmaia** [comment]
I found out that the configuration is read in the presets/styles instead of cz-cli. Example:
https://github.com/commitizen/cz-conventional-changelog/blob/master/index.js#L7

**Comment by Nargonath** [comment]
I'm not sure what you mean by that.

**Comment by fsmaia** [comment]
I mean that `configLoader` is used by cz-cli to determine the preset, but preset with additional configurations must also call `configLoader` to load them, otherwise rc file configurations won't be read.

But IMHO this issue's main purpose is the lack of documentation concerning configuration files. A simple phrase in README like: "this project uses cosmiconfig" would be enough.

**Comment by prometheas** [comment]
Yes, agree with @fsmaia that the heart of this issue is the lack of documentation around the package's support of config files, though it's hard to know without confirmation from its creator, @zyy7259.

That said, assuming this is correct, the PR above does seem allow this issue to be closed…

**Comment by pmcelhaney** [comment]
For anyone following this thread I just created a PR to support cosmiconfig attached to #773
