### ISSUE TITLE
Take ownership of the commitizen-bot

### ISSUE THREAD

**Issue by kentcdodds** [commitizen/cz-cli#491]
Hey folks!

So a while back, I made @commitizen-bot which has been used to automate releases of commitizen packages. It's email address is `kent+commitizen-bot@doddsfamily.us`, so I'm getting npm emails when its tokens are used to publish packages or when new personal access tokens are added to its account on GitHub.

I'd love to be able to hand off control to someone else. I'll go ahead and change the email address to whatever you want. Thanks!

**Comment by jimthedev** [comment]
👋 @kentcdodds. I've changed the email and taken over the account. Thanks again!

**Comment by kentcdodds** [comment]
Cool. I'll try to update the email for the npm account as well. I'm having some trouble ATM. You'll probably get an email when I get it to work. Thanks!

**Comment by kentcdodds** [comment]
Just got confirmation that the email address was changed for the commitizen bot on npm :+1:
