### ISSUE TITLE
Great idea

### ISSUE THREAD

**Issue by stevemao** [commitizen/cz-cli#5]
Hi @jimthedev , Thanks for this module. The idea is really great. But I want to use a different approach to do this so I might just create another one. We could eventually merge in the future though. Will let you know once mine is done. Thanks.

**Comment by jimthedev** [comment]
Sure thing @stevemao. Let me know when it is done and we can put mentions in our Readme's or find a way to merge.

**Comment by stevemao** [comment]
Thanks @jimthedev

**Comment by stevemao** [comment]
@jimthedev I never had time to do this. But My originally thought was to use handlebars templates to generate the commit messages.

**Comment by jimthedev** [comment]
@stevemao I considered it for a while, then decided to just execute "prompter" function inside an adapter and people could capture input however they prefer. I pass in inquirer by default but they could accept input in other ways if they wish. My main goal right now is npm3 support and building comprehensive tests. Both are coming along nicely.

**Comment by stevemao** [comment]
What was the reason you didn't choose to use a templating engine?

**Comment by jimthedev** [comment]
Good question. I wanted to let the cli be as flexible as possible.

The adapters can use a template engine if they like. I just chose not to force any single template engine.  Each adapter can use es6 template strings, handlebars, ejs, jade, etc. As long as they produce a string, I don't mind. :) 

At the end of the day, the cli just wants the adapters to give it a composed string to commit. If someone wants to create a cz-conventional-commit-handlebars adapter that uses handlebars then they could do it very easily.

**Comment by stevemao** [comment]
:+1:
