### ISSUE TITLE
clear confusion

### ISSUE THREAD

**Issue by OussamaElgoumri** [commitizen/cz-cli#50]
when i run `commitizen init cz-conventional-changelog --save --save-exact` i get this output

```
Attempting to initialize using the npm package cz-conventional-changelog

********
WARNING: You are using czConfig in your package.json. czConfig will be deprecated in Commitizen 3. 
Please use this instead:
{
  "config": {
    "commitizen": {
      "path": "./path/to/adapter"
    }
  }
}
For more information, see: http://commitizen.github.io/cz-cli/
********

npm WARN install Couldn't install optional dependency: Unsupported
angular-seed@0.0.0 /home/oussama/Desktop/IContribute
└─┬ cz-conventional-changelog@1.1.4 
  └── word-wrap@1.1.0 

```

the message say, `Please use this instead` but the suggested config is the same in package.json, also what is the optional dependency?

**Comment by jimthedev** [comment]
@OussamaElgoumri Thanks for the feedback and for using commitizen! Looks like this is a confirmed bug. I will look into it.

With regards to the optional dependency error, you can probably disregard for now if you using Node 4 and Npm 3. There is an open issue about the optional dependency bug [here](https://github.com/npm/npm/issues/9204). There is also some more info [here](https://github.com/meanjs/mean/issues/1018) where someone tries a bunch of different node and npm combinations..
