### ISSUE TITLE
Update docs to use npx to install locally

### ISSUE THREAD

**Issue by giocodes** [commitizen/cz-cli#502]
Hi! With the latest node and NPM version I believe that we can do:
`npx commitizen init cz-conventional-changelog --save-dev --save-exact`

I'll be happy to create a PR if this is something we want to update the docs.

**Comment by jimthedev** [comment]
Yes!!! That’d be great. We need node 8 9 and 10 added to our Travis yaml too.

**Comment by mtliendo** [comment]
Is this still open to be picked up?

**Comment by jimthedev** [comment]
Yeah i think it is open

**Comment by giocodes** [comment]
Sorry, I intended to do this but I got lost on the Travis yaml comment. Is that also on the documentation?

**Comment by LinusU** [comment]
That doesn't have to be the same PR, feel free to just address the updated documentation 👍

**Comment by LinusU** [comment]
addressed the Travis thing here: https://github.com/commitizen/cz-cli/pull/531

**Comment by giocodes** [comment]
Cool, I'll create a PR soon for the documentation changes. Thanks
