### ISSUE TITLE
Locally installation messed up with Yarn

### ISSUE THREAD

**Issue by SevenOutman** [commitizen/cz-cli#527]
Hi team, first off thanks for creating this great tool!

I prefer a per-project installation of devDependencies so I'm also installing commitizen locally. The problem is I'm using Yarn as package manager, but when I run `./node_modules/.bin/commitizen init cz-conventional-changelog --save-dev --save-exact`, commitizen seemed to use `npm install` to install its packages, and `node_modules` just messed up.

So is there an option to run `commitizen init` with `yarn`?

**Comment by jimthedev** [comment]
Good question. Not at the moment but a --yarn flag is a pretty good idea.

**Comment by SevenOutman** [comment]
@jimthedev Cool. Looking forward to the update :)

**Comment by kenberkeley** [comment]
`commitizen init cz-conventional-changelog --yarn --dev --exact`
