### ISSUE TITLE
Bithound is dead

### ISSUE THREAD

**Issue by Fetz** [commitizen/cz-cli#529]
http://bithound.io/ is dead
![screen shot 2018-06-04 at 22 02 05](https://user-images.githubusercontent.com/1071113/40941505-f47ddc94-6842-11e8-8815-a05c7d7708fc.png)

IT didn't have the same luck as github :(

The bithound score in the readme should be removed and other places being used

**Comment by jimthedev** [comment]
True true. Want to put in a PR?
