### ISSUE TITLE
Open Collective CLI Breaks Build on CI

### ISSUE THREAD

**Issue by phil-lgr** [commitizen/cz-cli#544]
Anybody experiencing this: https://github.com/opencollective/opencollective-cli/issues/3 ?

**Comment by Oupsla** [comment]
Got the same error on CircleCi

Just add `DISABLE_OPENCOLLECTIVE=true` as environment variable

**Comment by ddymko** [comment]
I am running into this issue as well on concourse even with setting `DISABLE_OPENCOLLECTIVE=true`

Any ideas as to why this is happening?
