### ISSUE TITLE
not exit prompt after commit use nodejs 10 on windows10

### ISSUE THREAD

**Issue by calledT** [commitizen/cz-cli#545]
downgrade to nodejs 8 it work fine

**Comment by meszaros-lajos-gyorgy** [comment]
I also experience, that commitizen finishes, but never exits the task. I'm using commitizen v2.9.6, node v10.9.0 with npm v6.2.0 on windows 7. I'm using vscode's integrated terminal, which didn't have this issue prior to node update.

**Comment by calledT** [comment]
now I update nodejs to 10.9.0 and npm to 6.4.1, and it work fine eventually

**Comment by meszaros-lajos-gyorgy** [comment]
I've updated node to v10.10.0, npm to v6.4.1 and I still get this issue. Updating didn't solve anything for me, plus I would like to know what causes the issue in the first place.

**Comment by meszaros-lajos-gyorgy** [comment]
tried it in windows 7 command line and it's the same
