### ISSUE TITLE
Is there a way to override standard `git commit`?

### ISSUE THREAD

**Issue by anurbol** [commitizen/cz-cli#550]
Desired behavior:
1. install commitizen
2. run `git commit`
3. **see the same nice menu as when running `git cz`**

Current behavior:
1. install commitizen
2. run `git commit`
3. **NO nice menu as when running `git cz`, just default git interface**

I only interested in an answer, rather than actually requesting the feature.

**Comment by LinusU** [comment]
Depends, are you okay with setting it up yourself? Or are you wondering wether it could work out of the box in any project?

I don't know if it's possible to check in some git settings file in a repo to override the commit command. But you can do it globally on your machine if you want to. I _think_ just setting `GIT_EDITOR=git-cz` should do it 🤔

**Comment by anurbol** [comment]
Hi, @LinusU! "Or are you wondering wether it could work out of the box in any project?" - Yes I would like to know if it is possible. 

Isn't GIT_EDITOR just for setting text editor to make commit message? Anyway, setting an env variable does not satisfy the above criteria.

**Comment by LinusU** [comment]
I would think that this is impossible by design, because if it was possible you could trick git into running arbitrary command just by cloning a repository.

**Comment by anurbol** [comment]
Yes, but Commitizen could inject pre-commit hook or something. I guess you are right, there is no such feature, hence I can start implementing it by myself. But I'd like to keep this issue open for another couple of days, in case if there is someone who knows this undocumented or hidden feature... Thanks, @LinusU!

**Comment by anurbol** [comment]
I guess this issue is a duplicate of https://github.com/commitizen/cz-cli/issues/161, closing
