### ISSUE TITLE
Fix `new Buffer` deprecation warning by updating dependency

### ISSUE THREAD

**Issue by jacobq** [commitizen/cz-cli#552]
Right now, it seems this project uses a very old version of `inquirer`. What would it take to [upgrade that](https://github.com/commitizen/cz-cli/pull/541)? The main reason I care is because this seems to be blocking resolution of an [annoying deprecation warning when using `yarn` with Node >= 10](https://github.com/yarnpkg/yarn/issues/5477) because it uses `commitizen#inquirer#external-editor#chardet` (v0.4.2, which uses `new Buffer(...)` -- v0.7.0 updates to `Buffer.alloc(...)`, but it's not getting used because here `inquirer` is pinned to 1.2.3).

It looks like these are the breaking changes between 1.x and 6.x:

* 2.x: Drop support for node 0.10 and 0.12
* 3.x: Drop support for Node < 4
* 4.x: The core codebase went through a major es5 to 6 refactor. As such, we're **dropping support for Node 4.** This change will likely require changes to the community Plugins as es6 classes are enforcing more restriction (like constructor can only be invoked with new)."
* 5.x: Upgrade to RxJS v5 which updates a bunch of Reactive interface method names. For people not using the Reactive interface directly, this new major release should just work out of the box.
* 6.x: Update to Rx.js v6

**Comment by LinusU** [comment]
We could probably go to 3.x without problem, unfortunately going beyond that would be a breaking change from our side.

That being said, us passing `inquirer` to the adapter is deprecated, so we could probably create a breaking change that removes it 🙌

**Comment by karlhorky** [comment]
In case you want to go ahead with the upgrade after, I recently upgraded Inquirer.js from version 3 to 6 in `inquirer-autocomplete-prompt`. I tried to make the commits as granular as possible.

Maybe the pull request is good reference:

https://github.com/mokkabonna/inquirer-autocomplete-prompt/pull/64

**Comment by LinusU** [comment]
Nice!

The problem we have here is that we simply pass `inquirer` to the adapter, and thus we cannot really migrate since that code is beyond our reach 🤔

**Comment by jacobq** [comment]
Thanks for considering this; I've never used `inquirer` and am not even sure what "the adapter" is, so I don't think I should try to dive in and make a PR unless you're for sure never going to get around to this. 
A quick "band-aid" may also be possible if you could upgrade transitive dependency `chardet` to v0.7.0 without changing anything else (e.g. https://yarnpkg.com/lang/en/docs/selective-version-resolutions/ or https://github.com/rogeriochaves/npm-force-resolutions) as I don't think its API has changed significantly between that and its current version.
