### ISSUE TITLE
git-cz doesn't finish, doesn't return the prompt

### ISSUE THREAD

**Issue by meszaros-lajos-gyorgy** [commitizen/cz-cli#563]
Hi!

Since one of the recent updates (sadly I don't know which one exactly) when I run git-cz, the commit is created as expected, pre-commit hook also runs - if there is any -, but commitizen never exits after it's done. I also tried `git-cz --retry` and it works fine, there is no issue there.

There was a ticket addressing the same issue, but it's creator claims, that he solved the issue by updating his node version: https://github.com/commitizen/cz-cli/issues/545

I'm using node `10.10.0`, npm `6.4.1`, windows 7, commitizen `2.10.1` and cz-convencional-changelog `2.1.0`.

I've tried using it through visual studio code's integrated terminal and windows command line.

There are no error messages, so this is how far I got.

**Comment by meszaros-lajos-gyorgy** [comment]
Since `git-cz --retry` doesn't display options and it works fine, I have a hunch, that the real culprit might be the [Inquirer](https://github.com/SBoudrias/Inquirer.js) package.

**Comment by meszaros-lajos-gyorgy** [comment]
Possible related tickets on Inquirer side: https://github.com/SBoudrias/Inquirer.js/issues/667

**Comment by meszaros-lajos-gyorgy** [comment]
I've just realized, that commitizen uses version `1.2.3` Inquirer, while the latest version is `6.2.0`. `1.2.3` was released on Nov 13, 2016. Might worth trying updating it.

**Comment by meszaros-lajos-gyorgy** [comment]
On mac it works fine.

**Comment by meszaros-lajos-gyorgy** [comment]
Now the battery on my windows laptop is about to die on low charge and commitizen finished without any issue whatsoever. Is there a race condition somewhere in the code that causes this behavior?

**Comment by meszaros-lajos-gyorgy** [comment]
The power is back on and commitizen doesn't halt again.

**Comment by meszaros-lajos-gyorgy** [comment]
And now with a shorter commit, it finished correctly...

**Comment by meszaros-lajos-gyorgy** [comment]
Thank you for the information! I'll recheck this as soon as I can and I'll give feedback on whether the issue still present or not.

**Comment by jimthedev** [comment]
Cheers.

**Comment by meszaros-lajos-gyorgy** [comment]
Updated commitizen to `3.0.2` and all works fine! Closing ticket.
