### ISSUE TITLE
Release v2.11.0

### ISSUE THREAD

**Issue by qkdreyer** [commitizen/cz-cli#569]
Are you guys planning to release a new version soon ?
I'd like to get the dependencies update commits.

https://github.com/commitizen/cz-cli/compare/v2.10.1...master

**Comment by jimthedev** [comment]
We are working through it on the modernize-part-deux branch. We had
everything updated in modernize branch but it had some windows regressions.
In the future we will catch these sooner using MS dev ops instead of
appveyor.

-- 
Jim ForCy

**Comment by jimthedev** [comment]
FYI 3.0.0 has been released but please be aware that commitizen init seems to be having some issues resolving paths.
