### ISSUE TITLE
Commitizen no longer reporting "No files added to staging!" warning in dirty stage

### ISSUE THREAD

**Issue by designorant** [commitizen/cz-cli#585]
Commitizen correctly errors if there are no staged files *and* no changes, but fails to throw an error with no staged files in dirty state.

`v3.0.4`

**Comment by dbofmmbt** [comment]
It looks like #818 fixed it :tada:

**Comment by designorant** [comment]
Haha, what a blast from the past! Thanks for the update @dbofmmbt!
