### ISSUE TITLE
Test reports are not being published to Azure Pipelines

### ISSUE THREAD

**Issue by vagisha-nidhi** [commitizen/cz-cli#589]
Tests are running in the pipeline, but results are not being published for reporting. Azure Pipelines provides excellent reporting capabilities that help you with:

Easy analysis and troubleshooting for failed tests - the test reports show all relevant details (error message, stack trace, failing for how long, etc.) to make it easy to analyze failed tests.
Timing analysis - Test duration information helps you figure out long running tests, so that you can improve test collateral to speed up the pipelines.
Build-on-build trends/analytics help you get rich insights, for e.g., easily identify top failing tests.
The fix required is to use an XML reporter for mocha and update the YAML file to publish these test reports.

I am a Software Engineer on the Azure Pipelines team and will be happy to raise a PR to address this.

**Comment by jimthedev** [comment]
Would love to publish. Can you update the pr to revert the adapter change in the tests?

**Comment by jimthedev** [comment]
I updated and merged the PR.

Tests results seem to be posted: 
<img width="1019" alt="Screen Shot 2019-07-19 at 12 13 42 PM" src="https://user-images.githubusercontent.com/108938/61553017-ffde2480-aa1e-11e9-96ba-ae10ccd1cc7f.png">


Thanks!
