### ISSUE TITLE
Commitzen error in angular

### ISSUE THREAD

**Issue by Tauqeer1** [commitizen/cz-cli#596]
Commitzen is throwing the error while doing yarn run commit

**Comment by LinusU** [comment]
Could you share the error message & stack trace?

**Comment by jimthedev** [comment]
This is just a git message and doesn't really indicate anything specific to commitizen. You'd probably be getting it if you just used git commit as well. It just means that you had a previously aborted commit message. You can resolve it by deleting .COMMIT_EDITMSG.swp if you don't want to keep that commit message. If there is some more context around this I'd be happy to look further at it but currently I don't have any tracking that would let me know how you got to this state.
