### ISSUE TITLE
mac pro cant run git-cz

### ISSUE THREAD

**Issue by xxholly32** [commitizen/cz-cli#619]
macOS 10.14

run
```
npm i -g commitizen

git cz
```
![image](https://user-images.githubusercontent.com/6063358/56014911-bac49b00-5d29-11e9-920a-7d92b5e13801.png)

but i can run `npx git-cz` correctly with uninstall commitizen.

so when i commit i have to `npx` .

**Comment by Mayandev** [comment]
run `echo '{ "path": "cz-conventional-changelog" }' > ~/.czrc`

**Comment by xxholly32** [comment]
@Mayandev  ok its work

**Comment by zhangshichuan** [comment]
thx baby
