### ISSUE TITLE
is there a way to use git cz without installing anything globally, on a user-wide scope?

### ISSUE THREAD

**Issue by oupala** [commitizen/cz-cli#626]
I'd like to add commitizen to a git project, without having to install anything globally (system-wide or user-wide). I'd like all the configuration to be commited to git.

And I'd like commitizen to be available when entering `git cz` on the command line.

I've read the doc, but I did not manage to do that. Can anyone tell me if this is feasible? And if yes, how?

**Comment by LinusU** [comment]
As [outlined here in the readme](https://github.com/commitizen/cz-cli#using-the-command-line-tool) you can use `npx` to avoid having to install it globally.

> And I'd like commitizen to be available when entering git cz on the command line.

This is probably impossible without requiring your end users to install it somehow, since `cz` isn't a built-in git command...

**Comment by oupala** [comment]
If I understand it well, there is mainly two ways of using commitizen:

- either you install it locally but you have then to use `npx` syntax
- either you install it globally and you can then use the `git cz` syntax, but the commitizen requirement cannot be saved in npm package.json file, commited in git

Am I right?

As a result, as said @LinusU, it is not possible to commit the requirement of commitizen in package.json **and** to use the `git cz` syntax.

**Comment by jimthedev** [comment]
You can also put this in your bashrc / zshrc (make sure you restart or resource all your shells):

```
export PATH="$PATH:./node_modules/.bin"
```

This way you can be in the root of your project and run commitizen without needing it to be installed globally.

**Comment by oupala** [comment]
But bashrc are not commited in project git repositories.

It is a hard thing the enforce all developers to use commitizen easily. I don't see any easy and reliable way to do that. I was looking for something like:

- `npm install`
- edit your code
- `git cz`

But it seems that can't be that easy.

**Comment by binomialstew** [comment]
@oupala, when the `commitizen` package is installed, it creates a `git-cz` bin in `node_modules/.bin`. The `npx` command that @LinusU recommended will use the `git-cz` from that directory--meaning that the user does not need to install commitizen globally to use it.

**Comment by oupala** [comment]
@binomialstew in this case, the user has to use `npm git-cz` and not just `git cz`.

He will probably forgot to prefix the `git commit` command by the `npx` prefix.

**Comment by jimthedev** [comment]
The answer here is that the user should either add that path to their path if they'd like to not have to type it or can now use npx git-cz since https://stackoverflow.com/a/45164863 is a thing. When commitizen was originally written this wasn't a thing so you couldn't do this.
