### ISSUE TITLE
prepre-commit-msg git hook breaks IDE

### ISSUE THREAD

**Issue by eladchen** [commitizen/cz-cli#634]
Hi,

While integrating this tool, I noticed that my IDE started to misbehave when it performed git operations.

The example in the docs offers the following approach, which assumes /dev/tty is always available:
```shell
exec < /dev/tty && git cz --hook # <-- This fails when "not a tty"
```
The below uses a short-circuit to exit with an exit code of 0 in case tty is not available.
```shell
exec < /dev/tty && git cz --hook || true
```

Using the above solved a case where my IDE got killed during a rebase  
But I suspect that anything that interacts with git is susceptible to this pitfall.

Let me know if you agree, and i'll work on a PR.

P.S:

Found a case in point:  
https://stackoverflow.com/questions/55815650/lint-staged-commitizen-configuration-suitable-for-command-line-and-intellij/56555664#56555664

**Comment by jimthedev** [comment]
A PR would make my day. <3

**Comment by eladchen** [comment]
@jimthedev I'll get to you later tonight.

**Comment by eliraneliassy** [comment]
@eladchen - Thanks, just ran to the same issue!

**Comment by eladchen** [comment]
PR submitted. Sorry for the delay, have been busier than usual.

**Comment by micalevisk** [comment]
I'm still getting this error with Visual Studio Code in my Ubuntu :confused: 

This is what I'm using to fix that instead of just `exec < /dev/tty && git cz --hook --hook || true`:

```bash
( exec < /dev/tty && git cz --hook --hook ) || true 2> /dev/null
```
