### ISSUE TITLE
husky falls back to original git commit message prompt if I cancel when displaying commitizen prompt

### ISSUE THREAD

**Issue by brpaz** [commitizen/cz-cli#688]
Hello.
I am using Husky together with Commitizen to execute git-cz when doing a git commit.

I have defined the following configuration as stated in the documentation:

```
  "husky": {
    "hooks": {
      "prepare-commit-msg": "exec < /dev/tty && git cz --hook || true"
    }
  },
```

Everything works fine and I am prompted to choose the commit message from commitizen. 
The problem is if I hit  CTRL-C to cancel my commit, it just closes the commitizen prompt and falls back to the original git commit prompt. I want to abort everything in this case and dont do the commit.

I have tried to remove the "|| true" from the prepare-commit-msg command but it´s the same.

Not sure if it´s an issue of husky or commitizen.

Thanks for the help.

**Comment by shreyansh-zazz** [comment]
I am having the same issue. Also, the commitizen prompt is reprinting the options each time I type something.

**Comment by holson1** [comment]
Having the same issue - it looks like git-cz returns a 0 exit code even when CTRL-C'd. Not sure why commitizen traps the SIGINT but it should probably be surfaced. If it returns a non-zero exit code it should work with husky and prevent the standard git message from showing.

**Comment by tomdyqin** [comment]
i am having the sam issue.

**Comment by hdmr14** [comment]
commitizen using `Inquirer.js` for prompt.
[`Inquirer.js` traps`SIGINT`](https://github.com/SBoudrias/Inquirer.js/blob/3bbe28ce233938bc1c3f1e4ba13f26a8fb609ff0/packages/inquirer/lib/ui/baseUI.js#L26), and It have not any exit handlers.
I found implementation workarounds in [their discussion](https://github.com/SBoudrias/Inquirer.js/issues/405).

**Comment by jaikme** [comment]
For me, I'm trying to use the single command `git commit` and it prompt to choose my type:


```
husky > pre-commit (node v12.17.0)
ℹ No staged files match any configured task.
husky > prepare-commit-msg (node v12.17.0)
? Select the type of change that you're committing: (Use arrow keys or type to search)
❯ test:       Adding missing tests 
  feat:       A new feature 
  fix:        A bug fix 
  chore:      Build process or auxiliary tool changes 
  docs:       Documentation only changes 
  refactor:   A code change that neither fixes a bug or adds a feature 
  style:      Markup, white-space, formatting, missing semi-colons... 
```

#### Then I make de description: 
```
...
? Select the type of change that you're committing: chore:      Build process or auxiliary tool changes
? Write a short, imperative mood description of the change: 
  [-------------------------------------------------------------] 34 chars left
   chore: husky hook on git-cz
```
#### But it's falling back to VIM to edit COMMIT_EDITMSG:
 
 ```
chore: husky hook on git-cz
~                                                                                                                                           
~                                                                                                                                           
~                                                                                                                                           
~                                                                                                                                           
~                                                                                                                                           
~                                                                                                                                           
~                                                                                                                                           
~                                                                                                                                           
~                                                                                                                                           
~                                                                                                                                           
~                                                                                                                                           
"~/repo/.git/COMMIT_EDITMSG" [noeol] 1L, 27C
```
___
#### My pakcage.json husky config:
```
...
"husky": {
    "hooks": {
      "pre-commit": "lint-staged",
      "prepare-commit-msg": "exec < /dev/tty && git cz --hook || true",
      "commit-msg": "commitlint -E HUSKY_GIT_PARAMS"
    }
  },
```




-> Some can help me with this issue? There is some "thing" to avoid open the `COMMIT_EDITMSG` or is the default behavior?

**Comment by praveenpuglia** [comment]
Has there been any fix to this?
I am on 4.2.4 but I still have the same issue. If I hit `Ctrl` + `C` while answering all the questions, it falls back to vim and then that commit message is used.

**Comment by Dunky13** [comment]
Having this issue as well, sadly throws me to vim commit message if I use `CTRL+C` 

```js
    "commitizen": "^4.2.4",
    "git-cz": "^4.8.0",
    "husky": "^7.0.4"
```
