### ISSUE TITLE
NPM Audit Vulnerability

### ISSUE THREAD

**Issue by joepaquette** [commitizen/cz-cli#715]
Moderate Vulnerabilty: Prototype Pollution
Package: minimist
Patched in: >=1.2.3

See https://npmjs.com/advisories/1179

**Comment by duniul** [comment]
There's a PR up for this, it just needs to be merged by someone: https://github.com/commitizen/cz-cli/pull/713

**Comment by joepaquette** [comment]
NOTE: PR  [#713](https://github.com/commitizen/cz-cli/pull/713) will not resolve this vulnerability. The minimum version for minimist is 1.2.3. The PR only bumps the version to 1.2.2.

**Comment by duniul** [comment]
My bad, misread the version number! I wonder why Dependabot doesn't update it to the latest version?

**Comment by bajtos** [comment]
AFAICT, there are two bot-contributed PRs open to resolve this issue:

- fix(deps): update dependency minimist to v1.2.2 [security] #712 by Renovatebot
- chore(deps): bump minimist from 1.2.0 to 1.2.3 #721 by Dependabot

Both pull requests are failing on CI, I think the problem is Windows specific. I am not able to view logs from Azure Pipelines, the AppVeyor log is complaining about incorrect CI setup.

https://ci.appveyor.com/project/jimthedev/cz-cli/builds/31474679
```
Build started
git clone -q --branch=renovate/npm-minimist-vulnerability https://github.com/commitizen/cz-cli.git C:\projects\cz-cli
git checkout -qf a162b40f6e7373887ac577187306bf8b5b477cc4
The build phase is set to "MSBuild" mode (default), but no Visual Studio project or 
solution files were found in the root directory. If you are not building Visual Studio 
project switch build mode to "Script" and provide your custom build command.
```

**Comment by bajtos** [comment]
Ping @jimthedev, what's the status of this project? I see the last commit was merged in August 2019. I am an open-source maintainer myself, so I totally understand if you don't have time or energy to maintain this project going forward. Do you have any recommendations for us, commitizen users, how to deal with the current security warning and/or help this project to become actively maintained again?

**Comment by cjolif** [comment]
Note that I'm coming here because I have this very security warning with `cz-conventional-changelog` so once fixed it would be good to get `cz-conventional-changelog` use the new minimist version as well.

**Comment by jimthedev** [comment]
@bajtos https://dev.azure.com/commitizen/cbf3c633-a6bc-43ce-ae50-fe434d244768/_apis/build/builds/851/logs/50 is the current error I am working through.  For some reason windows fails with a ShellJS internal error, something about permissions on package.json. Not sure why it is failing on windows.

**Comment by TJProgrammer** [comment]
The pakage `core-js` also needs to be updated ...
```
warning: commitizen > cz-conventional-changelog > @commitlint/load > babel-runtime > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
```
> From https://github.com/commitizen/cz-cli/issues/716

**Comment by hdmr14** [comment]
> 2020-04-07T20:06:50.5410420Z Error: EPERM: operation not permitted, lstat 'D:/a/1/s/test/.tmp/enduser-app/package.json'

the path looks like [not formatted by path.join](https://github.com/commitizen/cz-cli/blob/09ade0038fb9a3f7bed3e7175f8c334724c18406/test/tools/clean.js#L119)...?
separator should be `\` in Windows, but it's not.
I don't know whether this is because of that...

**Comment by hdmr14** [comment]
> @bajtos https://dev.azure.com/commitizen/cbf3c633-a6bc-43ce-ae50-fe434d244768/_apis/build/builds/851/logs/50 is the current error I am working through. For some reason windows fails with a ShellJS internal error, something about permissions on package.json. Not sure why it is failing on windows.

Apply below changes fixes ShellJS internal error and some errors.
These changes passed all tests with Windows 10 for me.
hope this helps.

```diff
diff --git a/src/commitizen/adapter.js b/src/commitizen/adapter.js
index 6878946..6765618 100644
--- a/src/commitizen/adapter.js
+++ b/src/commitizen/adapter.js
@@ -78,7 +78,7 @@ function generateNpmInstallAdapterCommand (stringMappings, adapterNpmName) {
 function generateYarnAddAdapterCommand (stringMappings, adapterNpmName) {

   // Start with an initial yarn add command
-  let installAdapterCommand = `yarn add ${adapterNpmName}`;
+  let installAdapterCommand = `npx yarn add ${adapterNpmName}`;

   // Append the necessary arguments to it based on user preferences
   for (let value of stringMappings.values()) {
```

```diff
diff --git a/src/commitizen/init.js b/src/commitizen/init.js
index 624d5c4..396f0ae 100644
--- a/src/commitizen/init.js
+++ b/src/commitizen/init.js
@@ -96,6 +96,8 @@ function init (sh, repoPath, adapterNpmName, {
   } catch (e) {
     console.error(e);
   }
+
+  sh.cd(__dirname);
 }

 /**
```

```diff
diff --git a/test/tools/clean.js b/test/tools/clean.js
index 5241dd6..2472351 100644
--- a/test/tools/clean.js
+++ b/test/tools/clean.js
@@ -116,6 +116,7 @@ function keep (sh, basePath, paths, n) {
 }

 function cleanPath (sh, tmpPath) {
+  sh.cd(__dirname);
   sh.rm('-rf', tmpPath + '/*');
   sh.mkdir(tmpPath);
 }
```

sh.cd() is changing process.cwd(). due to this behavior, process grab directory access until test exit even if we want remove it.

**Comment by LinusU** [comment]
A PR to remove ShellJS would be very welcome 😬 

Since the CI is current red for `master` anyway, I made a commit that fixes the vulnerable packages, by bumping minimist and running `npm audit fix`.

There are a number of dev-dependencies that would still need to be bumped though, which probably includes dropping support for older versions of Node.js...

**Comment by LinusU** [comment]
Fixed in commitizen@4.0.5, sorry for the delay everyone!

**Comment by hdmr14** [comment]
@LinusU thanks update packages!

Tests failed on windows is not caused by ShellJS.
It's just a problem with change working directory(even if not via ShellJS) for exec some command(`git`, `npm`) in temporally directory for tests.

Could you approve above fix(`sh.cd(__dirname)`, `npx yarn add`)?
If so, I'll create a PR and test non-Windows platforms as well.

**Comment by LinusU** [comment]
@hdmr14 I have a branch that I made last night which I think solves it by not using `childProcess.{spawn,exec}` and explicitly passing the working directory. Just fell asleep before I got time to commit and push 😅 

I'll push it later today, and then maybe you can review it for me?

**Comment by hdmr14** [comment]
@LinusU what a nice work! off course, I can 😍

**Comment by LinusU** [comment]
Posted a PR here #729 , but the test is still failing on Windows, although in a slightly different way...
