### ISSUE TITLE
Python invalid syntax on commitizen init

### ISSUE THREAD

**Issue by Gunlek** [commitizen/cz-cli#743]
## Description:
While trying to initialize commitizen on a repo, I'm getting the following error:

## Console log
`gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.15.3 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Command failed: D:\Programs\Python\Python37\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "D:\\Programs\\nodejs\\node.exe" "D:\\Programs\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
\node_modules\node-memwatch
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

## Environment:
Node.JS / React project
Python3.7 installed
`npm install -g commitizen` executed
Issue while running `commitizen init cz-conventional-changelog --save-dev --yarn --save-exact`

**Comment by Gunlek** [comment]
Fixed if Python 2.7 is used

Is Python 3 update possible ?

**Comment by dmwelch** [comment]
Can you verify that your node-gyp setup is correct? https://github.com/nodejs/node-gyp#on-windows

**Comment by Gunlek** [comment]
Working correctly after changing node-gyp python version to 3.8

**Comment by dmwelch** [comment]
Awesome - I'll close the issue then.  Thanks for checking!
