### ISSUE TITLE
Installing commitizen failed globally and locally

### ISSUE THREAD

**Issue by AbderrazzakB** [commitizen/cz-cli#747]
When I'm trying to install commitizen I get this error:

> λ npx commitizen init cz-conventional-changelog --save-dev --save-exact
> npm ERR! Unexpected end of JSON input while parsing near '...brbIJWQRPuenQhOJe/KJO'

- Windows 10
- NPM 6.14.2
- NODE 12.16.2

**Comment by dmwelch** [comment]
Did you run `npm install -g commitizen`?

**Comment by AbderrazzakB** [comment]
I had to clear the npm cache, and then the installation did work fine, I think that was the problem.
