### ISSUE TITLE
Skip some of the questions

### ISSUE THREAD

**Issue by lcesarmonteiro** [commitizen/cz-cli#749]
Is it possible to skip some of the questions? 
Basically I just want the type and the short message. Eventually I will need to inform the related issue

Is it possible to just ignore all the other questions?

**Comment by dmwelch** [comment]
You can use the `cz-customizable` adaptor and configure it to skip the questions you don't want.  

See https://github.com/leoforfree/cz-customizable/blob/master/cz-config-EXAMPLE.js for an example configuration file with the `'body'` question skipped.
