### ISSUE TITLE
Support custom template for issue number.

### ISSUE THREAD

**Issue by asm0dey** [commitizen/cz-cli#755]
We at JetBrains are using Youtrack as issue tracker and it supports automatic closing of issues too, but template is little bit different: for example `#BDIDE-111 Fixed`.

Could you please add support for changing template for fixed issue? Thank you!

**Comment by dmwelch** [comment]
Hi @asm0dey, did you take a look at the [adaptors](https://github.com/commitizen/cz-cli#adapters)?   

If you don't find one that works for your particular use case, we've built the project specifically so new adaptors can be created around new tools.  Take a look at the `engine.js` file in the [cz-conventional-changelog](https://github.com/commitizen/cz-conventional-changelog/blob/master/engine.js) to see how you might create an adaptor that would work specifically with Youtrack.  If you do, please consider submitting a PR to link it on the README.  Happy hacking! ;-)

**Comment by asm0dey** [comment]
Thank you so much, didn't see it! I think this issue can be closed.
