### ISSUE TITLE
check for staged commits before questionnaire

### ISSUE THREAD

**Issue by waynevanson** [commitizen/cz-cli#785]
Sometimes I forget to do `git add <path>`, so when I get to the end of the cli quesitonnaire, it gives me an error.
I then have to do `git add <path>` and then run the cli, going through the questionnaire again.
Doing this on a breaking change is frustrating because I have to rewrite what I just wrote.

Was this intended for a reason? If so, why? I'd like to hear about it.

**Comment by travi** [comment]
i might not be the right person to answer your direct question, but you can avoid needing to go through the wizard a second time in cases like this using the [`--retry` flag](https://github.com/commitizen/cz-cli#retrying-failed-commits)

**Comment by waynevanson** [comment]
@travi  NICE! That's a good workaround for now, but will still love to hear what others have to say.

**Comment by eduardocanellas** [comment]
I agree with @waynevanson. As the CLI is able to know upfront that there's nothing staged, I don't see why it asks for information. I think it would be better to just send a message like "There's nothing staged! To commit, first stage something."

Actually, I've just checked out the open issues and this one looks to be related to #585. Fixing that issue would resolve this one too.
