### ISSUE TITLE
Silly question about commitizen and use for C/C++ repos

### ISSUE THREAD

**Issue by krish2487** [commitizen/cz-cli#790]
Hello,

Please excuse my rather stupid and silly question, for I am trying to learn.
I m a firmware ( C /C++ ) engineer working with microcontrollers. 
I m trying to adpot good, standardized practices for maintaining projects - personal and professional.

I was wondering, if I can use standard git flow + commitizen as a SOP for commiting my changes to the repo.
Are there any drawbacks to doing so? 

The getting started guide deals with changes and customizing the package.json and such which
1. I dont understand much (if at all) 
2. Are not really something that might exist on a C /C++ repo with a make build system.

I was hoping a good samaritan might indulge a noobs request and handhold me to use this tool.
Nothing exotic or esoteric, a standard conventional commit style (which I understand is the default) will be a good starting point.

At this point, I installed the tool using pip and npm, but am lost beyond that.

Thanks in advance and I apologize if this seems like a rather irrelevant question in this place.

**Comment by LinusU** [comment]
Hello, sorry for not getting back to you earlier!

You can absolutely use this tool in a c/c++ project. You could install commitizen globally, and have a `package.json` file with your config ☺️

**Comment by krish2487** [comment]
@LinusU  Thanks. :-)
No worries about not getting back. I figured it was okay. I posted the same question here
https://github.com/commitizen-tools/commitizen
and was told it was okay. I have no idea if both this repo and the link above are from the same maintainers, but both seems to serve the same purpose.

I was thrown off by the package.json file and have little clue as to how to use it. Hence the question.  I forgot to close the issue. My bad. 

Thanks anyway

**Comment by ShaneKosieradzki** [comment]
@LinusU I'm not familiar with `package.json` but it seems to be a JavaScript construct. Is it possible to use commitizen without using a JavaScript config file? That is, is there some Commitizen specific config file that can be used in the place of `package.json`?
