### ISSUE TITLE
Commitizen Logo in SVG?

### ISSUE THREAD

**Issue by bromso** [commitizen/cz-cli#800]
Can you please make your logo available in SVG?

https://images.opencollective.com/commitizen/logo/256.png

TIA

**Comment by bromso** [comment]
I hope you guys don't mind but I recreated it. I'm pretty new here and I don't have rights to push or make a pull-request. So I've made them available on a shared Google Drive. But would be great if I could push them myself (if you want them of course).

https://drive.google.com/drive/folders/1arGk0Y_fbs4dvz02RUJKZLn_OsfTSm3i?usp=sharing

**Comment by fsmaia** [comment]
Up! This would be very helpful in the VSCode integration.

**Comment by dmwelch** [comment]
@bromso plz make a PR and I'd be happy to merge it in for you.  If you fork the project, you will be able to make a branch there and create a PR back to here.  Thx!

**Comment by fsmaia** [comment]
@bromso, if you will I can make the PR for you, not only in this repository but in vscode-icons too.

**Comment by bromso** [comment]
@dmwelch @fsmaia I've forked your project, added all the logos, in different **formats** _(png & svg)_, **colors** _(white, black & the brand blue)_ & **resolutions** _(PWA icon sizes)_.

You can find them here in a branch called logo. Now what do I do? :)
https://github.com/commitizen/cz-cli/pull/878

**Comment by bromso** [comment]
You can also take charge of the file I made in Figma to recreate your logo.
https://www.figma.com/community/file/1045298312375103142/Commitizen-logo

**Comment by dmwelch** [comment]
Will take a look

**Comment by bromso** [comment]
I've made an issue in https://svgporn.com/ so you guys can get some more exposure. 😄 

https://github.com/gilbarbara/logos/issues/480

**Comment by fsmaia** [comment]
Just opened the PR in vscode-icons:
https://github.com/vscode-icons/vscode-icons/pull/2869
