### ISSUE TITLE
[security] bump `find-node-modules` to `2.1.2`

### ISSUE THREAD

**Issue by myovchev** [commitizen/cz-cli#825]
`find-node-modules` depends on merge, which has [security issues](https://npmjs.com/advisories/1666). Currently `find-node-modules` package is set to `v2.0`. The issue is resolved at the latest package version `2.1.2`.

**Comment by mybrainishuge** [comment]
https://github.com/commitizen/cz-cli/pull/824

**Comment by dmwelch** [comment]
Addressed in #842
