### ISSUE TITLE
npm audit vulnerability from "merge" package

### ISSUE THREAD

**Issue by h13o** [commitizen/cz-cli#827]
"merge < 2.1.1" package shows deprecation.
I think updating the package to 2.1.1 will solve this issue.

About Vulnerability
https://snyk.io/test/npm/commitizen/4.2.3
https://snyk.io/test/npm/merge/2.1.0

merge 2.1.1 fixed the vulnerability
https://snyk.io/test/npm/merge/2.1.1

**Comment by mybrainishuge** [comment]
See https://github.com/commitizen/cz-cli/issues/825 and https://github.com/commitizen/cz-cli/pull/824

**Comment by h13o** [comment]
Thanks!
