### ISSUE TITLE
Initialization error

### ISSUE THREAD

**Issue by Hollelihanqi** [commitizen/cz-cli#884]
I use the follwing command
npx commitizen init cz-conventional-changelog --save-dev --save-exact
The following error occurred：
![image](https://user-images.githubusercontent.com/31592701/146388474-6d55229d-f461-4aa3-a02b-f2207592d274.png)

I need help！
Thank you so much

**Comment by eduardo3g** [comment]
Same here running Ubuntu.

**Comment by Alahel** [comment]
Same there on a fresh manjaro

**Comment by TMInnovations** [comment]
Same here on Windows 10
