### ISSUE TITLE
help: strange behaviour in window cmd with commitizen

### ISSUE THREAD

**Issue by codenoobforreal** [commitizen/cz-cli#899]
![image](https://user-images.githubusercontent.com/18373253/152828446-6a65633a-db34-467c-997c-a5093bd24b3b.png)

after pressing any key:
![image](https://user-images.githubusercontent.com/18373253/152828567-dd897bae-60dc-4ee1-bc25-a1d71a792254.png)

**Comment by rpelizza** [comment]
same here

**Comment by valdney89** [comment]
Same problem here when use hook (husky). 

Work fine with cz direct command.

**Comment by Zhengqbbb** [comment]
emmm... not a commitizen problem. It should be that inquirer.js failed to clear the screen. If you try to use git bash terminal, will there be such a problem?
