### ISSUE TITLE
Security vulnerability with module ansi-regex 3.0.1

### ISSUE THREAD

**Issue by NorthDecoder** [commitizen/cz-cli#931]
Snyk notes:
![snyk-notes-ansi-regex-vulnerability](https://user-images.githubusercontent.com/9598008/166121287-95c7e403-b96d-450f-b672-9e827443195c.PNG)

**Comment by ryansonshine** [comment]
Related: https://github.com/commitizen/cz-cli/issues/914#issuecomment-1131383383

**Comment by ryansonshine** [comment]
Details and a potential fix: https://github.com/commitizen/cz-cli/issues/914#issuecomment-1131383383

**Comment by OmgImAlexis** [comment]
This can be closed https://github.com/commitizen/cz-cli/issues/914#issuecomment-1186543431

**Comment by NorthDecoder** [comment]
Confirmed at https://snyk.io/test/npm/commitizen/4.2.5
