### ISSUE TITLE
Possible bug with terminal prompt colours?

### ISSUE THREAD

**Issue by afgallo** [commitizen/cz-cli#939]
Hi there,

I have this weird behaviour where my terminal goes all fuzzy when I run commitizen through a husky hook. This doesn't happen when I run `npx cz` as per screenshot below:

![image](https://user-images.githubusercontent.com/9999415/170392229-5592b0e6-614f-47e1-87cb-9643ed0b9686.png)

What's interesting is that this had been working for a very long time. I wonder if this was a result of an update to latest commitizen version?

**Environment info:**
MacOS **12.4**
node **16.15**
git **2.36.1**
commitizen **4.2.4**
cz-conventional-changelog **3.3.0**

**Husky hook:**
```bash
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

exec < /dev/tty && npx cz --hook || true
# also tried exec < /dev/tty && node_modules/.bin/cz --hook || true
```

Thanks a lot for looking into this issue!

**Comment by techmunk** [comment]
This was casued by a change in git 2.36.0. Revet git to a version prior to this and you will see the issue "goes" away.

You can read more about it at https://lore.kernel.org/git/xmqqfskgz9sb.fsf@gitster.g/t/

**Comment by afgallo** [comment]
Thanks @techmunk, I've reverted to git version 2.32 (MacOS default) and it works now. I would've preferred to revert to a homebrew supported version but it seems they only have the latest

**Comment by ting772** [comment]
same problem,but i find a work-around,no need to revert to a version below 2.36.0,  my screenshot shown as below
![image](https://github.com/commitizen/cz-cli/assets/73220578/893d63d3-6b4c-4248-9c83-35fbf5cf437e)
move up/down my arrow,another shot
![image](https://github.com/commitizen/cz-cli/assets/73220578/33a4514b-66d2-4070-89ac-233dc4997f17)

here is my code:
![image](https://github.com/commitizen/cz-cli/assets/73220578/51c6d339-700d-4657-9d5f-08e5fa911d86)
