### ISSUE TITLE
I need to configure multi plugins inside `package.json` config

### ISSUE THREAD

**Issue by tomavic** [commitizen/cz-cli#947]
I need to configure multi plugins at the same time. For example `cz-conventional-changelog` and `cz-emoji-conventional`. How is it not available till now, to configure it like this:

```json
  "config": {
    "commitizen": {
      "path": ["cz-conventional-changelog", "cz-emoji", "cz-conventional-changelog-for-jira"]
    }
  }
```

This is hardly required 🚀

**Comment by Zhengqbbb** [comment]
Why do you need to configure so many adapters ?

**Comment by tomavic** [comment]
@Zhengqbbb For example

I want to use conventional changelog with commitlint and gitmoji. I can share with you what I have got so far from config files and git hooks.

The problem is I have to let go usage of gitmoji in favour of changelog.

**Comment by antonkharkhonov** [comment]
@Zhengqbbb in my case, I need to use `cz-conventional-changelog-for-jira` for jira ticket detection and `cz-customizable` to disable some steps and add more scope actions

**Comment by Zhengqbbb** [comment]
@tomavic @antonkharkhonov 
I think i can solve your needs, come and use my adapter, if you have any questions, send an issue

**Comment by Zhengqbbb** [comment]
@antonkharkhonov 

>  for jira ticket detection 
I'm not sure about the use of jira ticket detection, is it the ISSUE ID if yes, if he can get it by command then it can be combined with default scope for better experience

**Comment by tomavic** [comment]
@Zhengqbbb Yes I have another issue with changelog and emojis too. I am using semantic release which can't detect changes because of emojis. I figured out that I may add the emoji to the subject instead of beginning of commit message. Same as you did 😉😉

Let me try your adapter and give you a hint if that works. But I need to know if commitizen is able to support multi adapter.

**Comment by Zhengqbbb** [comment]
> @tomavic But I need to know if commitizen is able to support multi adapter.

No. Adapters you can understand to generate plugins for **UI plugins** and messages

Anyway, would you like to answer three rounds of questions in the CLI? 🤯👀

**Comment by tomavic** [comment]
> @Zhengqbbb, Anyway, would you like to answer three rounds of questions in the CLI? 🤯👀

Of course no, less questions is always fine. 

I am checking `cz git` right now and it seems amazing. I will try it out in a separate Angular app, and a separate Angular library workspace. 

If there are some questions I will post that there. 

I am going to close this issue as there is nothing to be discussed here 😉🚀
