### ISSUE TITLE
Changelog not generating when using github squash & merge

### ISSUE THREAD

**Issue by bavedarnow** [commitizen/cz-cli#950]
When merging pull requests using githubs "[squash & merge](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-commits)" feature, it seems like the cz bump processes correctly, but changelog generation does not.

Doing a `cz check` against the range fails the commit validation. The commit message of the squashed PR looks something like this:

```
PR Title here (#123)

refactor: aaaa

fix: bbb
```

and when doing a `cz changelog {version_number}`, I get an empty changelog, but expecting
```
## version (date)

### Fix
- bbb

### Refactor
- aaaa
```

The only solution I have is to disable "squash and merge", as well as "create a merge commit", and only enabling "rebase and merge"

**Comment by wojtekxtx** [comment]
Experienced this also. Think this is a bug.

**Comment by bavedarnow** [comment]
I made this in the wrong repo. Opened it here https://github.com/commitizen-tools/commitizen/issues/651

**Comment by wojtekxtx** [comment]
@bavedarnow never mind. My prev comment still holds the truth.
