### ISSUE TITLE
When I run git cz it goes to .git/COMMIT_EDITMSG

### ISSUE THREAD

**Issue by Lete114** [commitizen/cz-cli#959]
Instead of showing the interactable options on the command line, it comes up with edit `project/.git/COMMIT_EDITMSG`, what is the problem?

![image](https://user-images.githubusercontent.com/48512251/206993667-19cda966-e29c-4ce9-a7d1-723800bc0dfc.png)

**Comment by thoroc** [comment]
What was the issue DenverCoder69?

**Comment by ArifulH8** [comment]
@Lete114 How did you fix this issue?

**Comment by lete114** [comment]
Create a `.czrc` file in your `home` directory, with `path` referring to the preferred, globally-installed, `commitizen` adapter

https://github.com/commitizen/cz-cli?tab=readme-ov-file#conventional-commit-messages-as-a-global-utility
